### ISSUE TITLE
Demonmasster bugnat

### ISSUE THREAD

**Issue by Demonmasster** [DragonFire/panda#101]
поради голям брой постижения героят ми е бъгнат . така съм чул така разправям !

**Comment by AnTOLI** [comment]
Трява ти изтрят ach на героя.

**Comment by Demonmasster** [comment]
Обясниха ми за процедурата , после би трябвало да ми ги върнат предполагам ?

**Comment by Attractivee** [comment]
До колкото разбрах, ще ги върнат след като се разбере кои са проблемните.

**Comment by Demonmasster** [comment]
Драгоне , що го затваряш туй ишу , при положение , че проблема все още е налице ?
