### ISSUE TITLE
NPC:  "Ensorceled Colossus"

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#12]
Това NPC не би трябвало да атакува играчите, трябва да е неутрално.И само когато играч го атакува, то да отвръща.

**Comment by DarkAngel39** [comment]
http://www.wowhead.com/npc=45586 wowhead го показва като агресивно, според ytdb за 4.3.4, фракцията му трябва да е 2334 за А и Н. Не мога да проверя дали това е неутрална или агресивна фракция.

**Comment by 3DViking** [comment]
mersi,
UPDATE `creature_template` SET `faction_A`='2334', `faction_H`='2334' WHERE (`entry`='45586');
