### ISSUE TITLE
NPC: Skymaster Skyles

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#120]
http://www.wowhead.com/npc=44244/skymaster-skyles
Това NPC е с грешен левел, HP и неможе да се лети чрез него.

**Comment by DarkAngel39** [comment]
UPDATE `creature_template` SET `gossip_menu_id`=6944,`minlevel`=90,`maxlevel`=90,`faction_A`=1604,`faction_H`=1604,`npcflag`=8193,`unit_flags`=32768 WHERE `entry`=44244; -- Данните са от ytdb 4.3.4. НПЦ-то е обновено на пач 5.2 (от ниво 85 на ниво 90) и за това в wowhead пише "Added in patch 5.2.0", но всъщност си е там от 4.Х и би трябвало exp=3, а не на 4.
