### ISSUE TITLE
NPC: Wise Ana Wu

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#134]
http://www.wowhead.com/npc=60139/wise-ana-wu#.
Това NPC, трябва да е на една лотка, но е потънало под земята и неможе да се вземе quest от него, дори когато отидем под водата.

**Comment by Attractivee** [comment]
Оказа се, че само понякога се бъгва!Добре е да го погледнете все пак.

**Comment by Funkedelica** [comment]
Когато умреш там и се вземеш ,npc-то си е на лодката

**Comment by Enragelolz** [comment]
relog do / na lodkata i shte vijdash npc-to gore
