### ISSUE TITLE
A.I.D.A. Communicator a.i.d.a. communicator you don't meet requirements for that quest

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#14]
По-принцип този quest drop предмет от вида Common quest starting items
Така, че не би трябвало да изисква нищо за да се започне quest-а който започва от предмета, но изписва:
A.I.D.A. Communicator a.i.d.a. communicator you don't meet requirements for that quest

**Comment by Attractivee** [comment]
Оказа се, че може да се приеме questa след като изпълниш един определен quest, не знам точно кои.

**Comment by DarkAngel39** [comment]
http://www.wowhead.com/quest=27755 най-вероятно.

**Comment by Funkedelica** [comment]
Снощи го минах - иска левел 84
