### ISSUE TITLE
Tentodor-Вашият всеобщ любимец.

### ISSUE THREAD

**Issue by Tentodor** [DragonFire/panda#147]
Moje li da mi bude opraven paladina Tentodor,koito ima problemi s achievmenti i ne moje da se igrae s nego.Kato vlqza i izchakam 2-3 sekundi zabiva i ne moje da se pravi nishto=
http://i61.tinypic.com/10wqtk9.jpg

**Comment by ongamex** [comment]
пробвай да лефтнеш гилда в тия 2-3 секунди от чата /leaveguild или нещо такова
