### ISSUE TITLE
 [Crane Mastery: Needlebeak]

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#152]
http://www.wowhead.com/quest=31262
http://www.wowhead.com/npc=63796
NPC-то за quest-а, липсва!

**Comment by AnTOLI** [comment]
Аз съм го репортнал.

**Comment by Attractivee** [comment]
Браво на теб :D, това не значи, че и аз немога да го репортна.

**Comment by AnTOLI** [comment]
Хаха еми браво ама нз дали че  го сложат. ;д

**Comment by Attractivee** [comment]
Оправено, браво.
