### ISSUE TITLE
Bugnati geroi

### ISSUE THREAD

**Issue by Roughneckrlz** [DragonFire/panda#166]
Molq pomognete slednite geroi v koito vlezna-roughneck,gon,heartvader freezvat WoW-a mi kato se logna i crashva,inache kato vlezq v nqkoi drugi geroi nqma takuv bug,molq pomognete.

S uvajenie:Roughneck

**Comment by marto0oo** [comment]
ako si v guild leavni q s komanda /gquit i 6te ti se orpavi :)

**Comment by Venci88** [comment]
BRAVO POMOGNA MNOGO !!! EVALA

**Comment by marto0oo** [comment]
np :) tova i na men mi se slu4i zatova go znam :)

**Comment by Roughneckrlz** [comment]
dnes se opravi no pochna pak da zabiva,opravete tozi bug molq vi...
