### ISSUE TITLE
Priest OP

### ISSUE THREAD

**Issue by marto0oo** [DragonFire/panda#167]
Така поповете са изклучителни бъггави.Пример:Dreamlord на 88лвл ми изхака 140к,което не е възможно 140 да си 90 лвл с пвп итеми срещу 90 пве ок става ама това е на 88 лвл,Смъквата за 1 сек и си мъртав. и 90 лвл и 87,88,89 лвл няма значение 1 сек и мъртав.Той не те бие,ти го ударяш и си на под 20 % хп!!! WOW
За съжаление не се досетих да снимам комбат лога като ми наби 140к това е моя грешка,но когото и да питате от алитата,който е срещал Dreamlord ще потвърди това,което казвам!!! Успех с Нурфа много ще съм благодарен.

**Comment by Roigbg** [comment]
Скоро го открих  и аз това нещо с моя поп.Това е бъг с Inner Fire,който незнайно как се стаква с Inner Will.Просто самият Inner Fire  нещо не е наред или поне за момент не е ..докато не си намахаш сам бъфовете.Въпросният Inner Fire ми взимаше цялата мана и съответно си стоеше редом с Inner Will-а.Но както казах това е до тогава докато не смениш спек или и аз нз точно да си махнеш сам бъфовете както аз направих след което неможех да пускам Inner Fire-а ,който ми стоеше по баровете(най-вероятно от wotlk изкаран) а този от Spellbook-а можех да го пускам и той си заместваше Inner Will-а както трябва ,тъй като не е възможно двата бъфа да са пуснати. :) Но за жалост попа ми в момента е бъгнат на loading screena и не мога да влеза та да ти кажа нещо повече но мисля че това обяснява нещата с нереалният дмг и хил :)

**Comment by marto0oo** [comment]
мхм много благодаря,надявам се,че гмтата са го видели и ще направят каквото е нужно :)

**Comment by ub4o13** [comment]
Ако става дума за един трол поп , той имаше 2 Inner fire-а едновременно , но бяха с различни ефекти , предполагам че или е някакъв бъг с магията от wotlk или е бъг с глифовете

**Comment by Roigbg** [comment]
![wowscrnshot_021114_190106](https://f.cloud.github.com/assets/6537784/2139428/c245c09e-933e-11e3-9ae8-66e8fc0e0593.jpg) мисля че за този трол става на въпрос.И да доста е интересно да се играе срещу него..особено ако ти направи 260к инстант :) Ама кво нали на него му е забавно...хорд е ..ГМ-те хорди и така...Незнам освен да смятате че това е нормално и балансирано ок ..А тоя кайш да продължава в същият дух това да е БЪГ или пък ЕКСПЛОЙТ не не съвсем нормално е да имаш 2 инер-а едновременно ..като имаш предвид че бъгат е ясен и в по-горен коментар съм го описал ....ОК.!

**Comment by marto0oo** [comment]
Така е просто играча,които играе си са кефи,вапроса е като оправят маговете,че ще го ядеееее и 1 каст няма да напраи :Д са радва докато има време,после ша си трие WoW-a!!! Обещавам му го!!!

**Comment by Mympa** [comment]
kato go gledam e na 250k Hp ... 90 lvl wow ....mnogo se  e nahapal toq.. az na 80 lvl s moq pop moga da si sloja Inner fire i inner will ednowremenno ... (skoro si otvorih accounta i go vidqh) gadno e da te kilvat instant-no . zasega shte e etaka ... shtoto GM-tata gi murzi .. da opravqt !!
