### ISSUE TITLE
Problem s Main Hero

### ISSUE THREAD

**Issue by Ivailo3007** [DragonFire/panda#170]
Shtom vlezq s main heroto sled nqkolko secundi mi zabiva.Syzdadoh 2 novi pri tqh nqma podoben problem.Main Heroto mi se kazva Beliskner 88 level.Molq opravete mi geroq.

**Comment by marto0oo** [comment]
Ако си в гилдия leftn-ия с команда: /gquit и си готов и нямаш проблеми.

**Comment by Ivailo3007** [comment]
Blagodarq ti mng :)

**Comment by marto0oo** [comment]
Няма защо,помагам когато мога :)
