### ISSUE TITLE
90lvl can't port pandaria

### ISSUE THREAD

**Issue by Enragelolz** [DragonFire/panda#173]
http://prntscr.com/2qjohk

**Comment by Mympa** [comment]
kakvo e tova snimka na geroq ti ... ne se vijda daje koi lvl e .. za da se portnesh do pandaria ti iska 85 lvl  min .. a kakto az vijdam ... ti mai go nqmash oshte !!! ili iskash da skipnesh celia cataclysm za da idesh do Pandaria !!! Neznam ...

**Comment by Enragelolz** [comment]
xahhxah.. Az sum realm first 85 mage i realm first 90 mage... ideqta na snimkata e GM-tata da vidqt, che acc-to mi e ogranicheno do wotlk neznaino zashto

**Comment by Mympa** [comment]
emi napishi po qsno .,.... samo ot tazi snimka ne se vijda nisho... az vijdam samo .. edin geroi koito ima nujda ot upgrade do 85 lvl ... neznam kak si go dignal do 90 lvl

**Comment by Enragelolz** [comment]
emi acc-to mi se bugna vchera.... predi tova nqmah nikakwi problemi... ne sum slojil snimka, na koqto mi se vijda levela, zashtoto gm-tata znaqt che sum 90-to nivo

**Comment by Mympa** [comment]
аз пък сега реших да си видя героя ...и да си сложа играта ама карък ... неще нещо и сега си цъкам Siege of Ogrimar!!! чакам някой да се събуди ... може да имат проблем сега незнам ..

**Comment by DarkAngel39** [comment]
Играта ти май не е upgrade. Отвори файла Config.wtf в папката WTF и виж какво пише като стойност на "SET accounttype " Ако пише SET accounttype "MP", значи играта е наред. Всяка друга стойност ще ти докара проблеми, понеже клиента ти пречи да идеш на мап, за който нямаш необходимия експанжън разрешен. Предполагам, че при теб пише SET accounttype "LK". Промени LK на MP и пробвай.

**Comment by Enragelolz** [comment]
pishe SET accounttype "MP" 
btw twa se sluchva samo s mage-a mi... imam drug geroi koito e 87 i moga da se portna v pandaria ..

**Comment by DarkAngel39** [comment]
Ако изчистиш WTF\Account папката става ли пак?

**Comment by Enragelolz** [comment]
nesum probval, no i sega nqma kak da stane, zashtoto neshto nemoga da se logna v servera

**Comment by DarkAngel39** [comment]
Off е май. И при мен е така.

**Comment by Enragelolz** [comment]
mxm

**Comment by AnTOLI** [comment]
darkangel кажи как се бъгват така героите с тия Achievements дето не може да влезеш в играта с тях. Бъг в базата ли е това. ;д

**Comment by DarkAngel39** [comment]
Не, предполагам че е dbc проблем. Също така и записването на action bar и голяма част от докладваните в тикетите липсващи npc може да са следстве от лоша dbc структура на сървъра. По този въпрос без съмнение се работи. Разбира се, това не е толкова лесно за оправяне, така че трябва да проявим разбиране.

**Comment by AnTOLI** [comment]
Фиксове за тоя сървер кои ги прави. Некои като github на тринити коре ли.

**Comment by DarkAngel39** [comment]
Доколкото знам, екипа на DF се занимава с ядрото като независим проект. Засега няма подобен публичен емулатор на 5.1.0а trinity с github репо и т.н. Репото на нашия сървър е private, понеже в противен случай конкуренцията ще го изкопира на техните сървъри.

**Comment by Enragelolz** [comment]
@DarkAngel39 
Nomera s delete na wtf a -y ne stava, problema e pak na lice..
qvno ot samiq server neshto mi se e setnalo acc-to do wotlk

**Comment by DarkAngel39** [comment]
Да, щом и това не тана, значи имаш проблем там.

**Comment by StDarkAngel** [comment]
За такъв тип проблеми пишете в helpdesk за да могат да ви обърнат внимание хората занимаващи се с онлайн поддръжка. Нека тук пишем само проблеми с ядрото за да можем да им търсим решение.
