### ISSUE TITLE
Disconnect non-stop ( проблема си седи )

### ISSUE THREAD

**Issue by stennka** [DragonFire/panda#175]
Deathmantle
testvah si vruzkata kum vsichko vuzmojno, stabilna bez problemi
edinstveno kum servera ima problemi vseedno me othvurlq
probvah da okliucha vsichki portove i da se opitam da igraq, nqma promqna

**Comment by Enragelol** [comment]
аз съм същият...и още много хора братле... дано да обърнат внимание. Преди малко даже ми изписа Please log in with battle.net account... след което ми заби на Connecting и до там. ;x
