### ISSUE TITLE
Постоянен disconnect 

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#176]
Здравейте, днес се появи следния проблем:
Когато вляза с паладина ( Attractivee ) поиграя 20-30 секунди и ме dissconect-ва от сървъра и това е непрекъснато, играта е НЕВЪЗМОЖНА!
Проверих всичко което се отнася до мен, влязах в WOTLK сървъра, там няма проблеми.
Така че, моля оправете го.

**Comment by Attractivee** [comment]
Тествах и се оказа, че проблема е в целия АКАУНТ.

**Comment by stennka** [comment]
problema ne e v akounta mai zashtoto priqteli mi igraqt sega s geroq i tqh ne gi disconnectva (imam sushtiq zabaven problem)

**Comment by Attractivee** [comment]
Така е, пробвах с още един акаунт, също ме изхвърля :(.Моля обърнете внимание!
Играта ни е ограничена без никаква алтернатива.

**Comment by Enragelol** [comment]
Аз също имам този проблем... още от вчера е, точно след 2рото голямо спиране едночасово на Server-a ... влизам с което и да е acc и имам 30,000 Latency...играя 20 секунди максимум и ме disconectva. Не е от интернета,защотото не ми лаги на нищо друго..само Pandaria Account v DF.Обърнете внимание, Моля!

**Comment by Davieba** [comment]
Не е от ACC!!! Аз влизах с Енрейджа и нямам проблеми с него ..даже го изпидирах в зоната на Undeadite. Проблема е нещо със сървъра. Мен лично пък ми се затваря играта,все едно бия ALT+F4.

**Comment by Attractivee** [comment]
StDarkAngel commented 2 hours ago
Правят мръсно и флудят realm сървъра за да не може никой да влезе. Чисто по нашенски.
Чакаме DF Team да си свършат работата :D

**Comment by stennka** [comment]
e kvo obshto trea da ima DDoSvaneto na servera s tova che opredeleni hora imat connection issues zaradi samiq server dokato drugi si cukat bez problem ( pri rabotesht ne krashnal server )

**Comment by Enragelol** [comment]
ЩЕ ИМА ЛИ СКОРО РЕШЕНИЕ ПО СКАПАНИЯ ПРОБЛЕМ ИЛИ НЕ ?! :@

**Comment by Attractivee** [comment]
Видях, че понякога преди да ме изхвърли изписва: 
you can only be on 10 channels at a time

**Comment by Vasilii1** [comment]
При мен играта стои на Connecting

**Comment by Attractivee** [comment]
Оправи се, БРАВО!
