### ISSUE TITLE
Gold is missing

### ISSUE THREAD

**Issue by ongamex** [DragonFire/panda#177]
като логнах днес(2.9,2013)  видях че липсва целия голд който бях събрал. Има и други които се оплакват. Конкретно аз героя е Imoogi

**Comment by pendulum91** [comment]
Имам същият проблем! Вчера си разпратих голда от алтовете на маина (Penduluum) събрах 50к голд, днеска логвам и гледам голда ми в начална позиция - 8к.....

**Comment by Mympa** [comment]
proveri li da ne bi da sa pak v altovete :) ako sa tam ne gi prashtai nanovo ..

**Comment by ongamex** [comment]
нито съм продавал, нито съм копувал Sprit-и , нещо такова се говори в world-а. Дори да съм го правил пак не виждам как е експлойт или нещо подобно....

**Comment by pendulum91** [comment]
Няма ги във алтовете ми..изчезнали са някъде. Дори не съм извършвал нещо свързано с пари преди да изчезнат!

**Comment by hogan04110** [comment]
И при мене се появи този проблем. Не стига че са ми бъгнати главните герои, ами сега и ми изчезна и много голд от друг герой....
