### ISSUE TITLE
Проблемът с Disconnect-a

### ISSUE THREAD

**Issue by Enragelol** [DragonFire/panda#178]
Очевидно не съм единственият, няма и да съм последният,който прави такава тема конкретизираща проблемът със сървъра. Вчера след ъпдейтовете (особенно второто дълго отсъствие на сървъра) много хора не могат да си влезнат с акаунтите,поради високо Latency и 20 секунда игра максимум, след което ги disconnect-ва. Аз съм от тази групичка...Когато имате време, моля обърнете внимание :)

**Comment by ub4o13** [comment]
Аз дори не мога да логна , стоя си на connecting  и това е , как да го оправя някой знае ли ?

**Comment by Enragelol** [comment]
Надявам се ГМ-тата да знаят....

**Comment by Enragelolz** [comment]
@Enragelol 
Spirai wow-a

**Comment by Enragelol** [comment]
@Enragelolz 
Спрян е ...като оправят Disconnecta ще се пуска отново ;]

**Comment by stennka** [comment]
tova e nashata vuzmojnost da zabozame filmcheta (koeto az pravq :D) Homefront ftw produljavam s drugi :D

**Comment by StDarkAngel** [comment]
Правят мръсно и флудят realm сървъра за да не може никой да влезе. Чисто по нашенски.
