### ISSUE TITLE
launcher

### ISSUE THREAD

**Issue by crazyg777** [DragonFire/panda#182]
this is my first time trying to join this server and it downloaded just fine and then i open game and try to log in (i have previously made account) and it just says connecting and doesnt do anything and then i hit "esc" to go back to log in screen and then try again and it says i dont have a battle.net account plz help me

**Comment by marto0oo** [comment]
SET locale "enUS"
SET installLocale "enUS"
SET realmlist "pandaria.guildszone.com"
SET hwDetect "0"
Open: WoW/WTF/Config and between 2 and 3 put SET realmlist "pandaria.guildszone.com" or 
SET locale "enUS"
SET installLocale "enUS"
SET realmlist "pandaria.guildszone.com"
SET hwDetect "0"
