### ISSUE TITLE
Connecting и до там :)

### ISSUE THREAD

**Issue by Vasilii1** [DragonFire/panda#184]
След като се опитам да логна играта стои на Connecting и след това излиза You must log in whith a Battle.net account username and password.
Някакви идеи ?

**Comment by ub4o13** [comment]
Да и аз от 2 дни съм така

**Comment by Enragelol** [comment]
Много хора имат същият проблем..и аз съм от тези хора... проблемът ми е абсолютно същият, даже ако имам късмета да вляза ме изхвърля след 20 сек ...  :x:

**Comment by Vasilii1** [comment]
Ама как така някои хора си играят без проблеми а други не могат да логнат ?

**Comment by Enragelol** [comment]
Не съм запознат,но се разрових малко и мисля,че е заради някакви портове...но нз до колко е вярно това... определни хора и техните connections не се свързват както трябва с портовете на сървъра... може да няма никаква логика това,което написах за разбиращите,но все пак това знам - това пиша.

**Comment by 3DViking** [comment]
можете ли да пробвате да сложите в wtf/config.wtf

SET realmName "Pandaria"

**Comment by 3DViking** [comment]
@Enragelol, какъв ти е интернет доставчика?

**Comment by ub4o13** [comment]
SET realmName "Pandaria" не помага

**Comment by 3DViking** [comment]
@ub4o13, какъв ти е интернет доставчика?

**Comment by ub4o13** [comment]
Powernet , http://www.powernet.bg/ до сега съм нямал такива проблеми

**Comment by 3DViking** [comment]
Пусни пусни ping wow.dragonfire-bg.net

**Comment by ub4o13** [comment]
Получавам всичко с 1ms при wow.dragonfire-bg.net , но когато пинг-вам  pandaria.guildszone.com таймаутва

**Comment by Enragelol** [comment]
@3DViking  Не мисля,че трябва да намесваме интернет доставчиците ни,защотото съм 3оо% сигурен,че НЕ Е от тях поради факта,че каквото и друго да правя и където и да влизам - проблем нямам...а и няма как след 2рото спиране на сървъра (в събота) повече от 10 player-а да не могат да си влезнат с акаунтите. ...а и това SET realmName "Pandaria" си го има в Config-a..въобще не съм го слагал нито съм го премахвал...Преди на WOTLK имахме същият проблем 30% от сървъра... тогава още имаше Realmlist.wtf и много добре помня,че го fix-вахме,като сменяхме реалмлиста от 80.72.79.66 на 80.72.79.67 и влизахме без проблем... и не след дълго,когато пак се бъгне ..отново връщахме на 80.72.79.66 :) така,че не може да ме убедите,че интернета ми не струва..мога да ви И докажа

**Comment by ub4o13** [comment]
От интернет доставчиците е най-вероятно , защото аз съм на powerner и tracert ми таймаутва , а един приятел на megalan без проблем пингва сървъра ..

**Comment by Enragelol** [comment]
az ne sym na power edi kvo si .. do sega ne sym imal problemi s net-a .. ...nqma kak 20% ot server-a da sme na edin i sy6t internet,che da imame tozi problem.. priqtelkata mi e s mnogo po-slab internet (vivacom) i problemi NQMA .. vliza si bez problem.. taka,che namerete reshenie na problema i sprete da izlizate s nomera "internet dostavchicite" ...problema ne e v tqx,a v server-a.  Ne moje sled proslovutite updateti v sybota 20% ot server-a da ne moje da vleze ... ;x nz kakvo sa pravili DF-to ama da tyrsqt problema pri tqx,zashtoto ne e ot shibanite ni internet dostav4ici!

**Comment by Attractivee** [comment]
http://prikachi.com/images.php?images/575/---
@3DViking както виждаш, няма проблеми.
Също така съм на 100% съгласен с @Enragelol

**Comment by ub4o13** [comment]
http://prikachi.com/images/702/7052702E.png
edit : сега успях най-после да вляза

**Comment by Vasilii1** [comment]
Към wow.dragonfire-bg.net и pandaria.guildszone.com  1мс връзката си е ок според мен проблема е някъде другаде.Интернета ми е от Powernet но нямам проблем с пингването. Проблема се появи както ви казва колегата Enragelol 
 "Не мисля,че трябва да намесваме интернет доставчиците ни,защотото съм 3оо% сигурен,че НЕ Е от тях поради факта,че каквото и друго да правя и където и да влизам - проблем нямам...а и няма как след 2рото спиране на сървъра (в събота) повече от 10 player-а да не могат да си влезнат с акаунтите. ...а и това SET realmName "Pandaria" си го има в Config-a..въобще не съм го слагал нито съм го премахвал...Преди на WOTLK имахме същият проблем 30% от сървъра... тогава още имаше Realmlist.wtf и много добре помня,че го fix-вахме,като сменяхме реалмлиста от 80.72.79.66 на 80.72.79.67 и влизахме без проблем... и не след дълго,когато пак се бъгне ..отново връщахме на 80.72.79.66 :) така,че не може да ме убедите,че интернета ми не струва..мога да ви И докажа"

**Comment by 3DViking** [comment]
проблема не е от твоя интернет доставчик, а от нашият. Пробвай сега да се свържеш, не трябва да има проблем.

**Comment by ub4o13** [comment]
Благодаря че го оправихте :)

**Comment by Enragelol** [comment]
@Attractivee и @Vasilii1 , Благодаря Ви за подкрепата (:

п.п. @3DViking Благодаря Ти за експедитивното решение на проблема ;]
