### ISSUE TITLE
lolz can't login AGAIN :X

### ISSUE THREAD

**Issue by Enragelolz** [DragonFire/panda#185]
Nadqvam se pak da mi opravite wara..
Poigrah nqkolko chasa, dignah 66 level i v edin prekrasen moment, kogato reshih da relogna: **_BOOM**_ geroq mi se bugna ...

http://prikachi.com/images.php?images/895/7050895x.png
http://prntscr.com/2r6zi8

**Comment by 3DViking** [comment]
try again

**Comment by Enragelolz** [comment]
amii .. pak **_ne stava**_

**Comment by 3DViking** [comment]
дай скайп

**Comment by Enragelolz** [comment]
asd
