### ISSUE TITLE
Играта забива след като вляза!

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#187]
След като си логна с героя ( Attractivee ) играта ми забива и колкото и да чакаш не се оправя.

**Comment by hogan04110** [comment]
Нищо чудно да се е бъгнал гилда....

**Comment by SymbolixDEV** [comment]
Iztriy sis cache papkata i WTF papkata i probvai da vlizash

**Comment by marto0oo** [comment]
Първо вие не чететели в world-a и в репортите тука,че гилдиите са бъггнати и има лимити на играчи!!! За да си орпавиш героя пишеш команда: /gquit и си готов моля спрямо това не пишете излишни теми за нещо,което се знае от всеки!!!

**Comment by marto0oo** [comment]
моля се затвори тоя репорт!!!

**Comment by Attractivee** [comment]
Проблема идва от гилдията, когато има 345 или повече хора идва този проблем, поне при нас е така.
