### ISSUE TITLE
Проблем с нивото на гилда

### ISSUE THREAD

**Issue by Llewella** [DragonFire/panda#191]
Гилда се казва "Onixya Warriors" колкото и куести да минаваме, не се вдига и на 1% лвл на гуилда. Нужно ли е гилд мастъра да направи нещо?

**Comment by marto0oo** [comment]
Не излиза ехп на гилда просто иначе се вдига спох

**Comment by Mympa** [comment]
a nqkoi znae li dali perk-s na guilda bachkat !!! nai veche 10% exp,Honor, Justice points Valor points ???ili ne ste oburnali vnimanie !!  i pak kazvam ... da vzemat da porabotqt malko zashttoto e dosada da se play

**Comment by marto0oo** [comment]
10 % ехп работи!!! др незнам хонора мисля,че да но др нз,понеже не работи пве аспекта!!!

**Comment by Llewella** [comment]
Ako se wdigo, to zashto ne se otkliuchwat skilowete?
