### ISSUE TITLE
Guild Perk, Mobile Banking

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#193]
http://www.wowhead.com/spell=83958/mobile-banking
Този Guild Perk, Не работи.Когато го пуснем не излиза нищо, само слага CD.

**Comment by marto0oo** [comment]
Ако не знаеш повечето спеллове от гилд нещата Не Работят и отделно как искаш да ти отвори банката и да ти изкара сандъка при положение,че гилдиите нямат Банка!!! Или поствате тема без да мислите!!!
