### ISSUE TITLE
Проблем при логване.

### ISSUE THREAD

**Issue by blackhunterr** [DragonFire/panda#195]
Проблема е само при един от геройте ми - Nomoresorrow Night Elf Rogue. Играта зарежда почти до края, кадето забива и до там. Стои така около 3 минути и дискънектва. Има ли решение на този проблем или да чакам :)

**Comment by muglata** [comment]
аз също имам този проблем герои в играта (lifestealer) благодаря за помоща

**Comment by blackhunterr** [comment]
![1](https://f.cloud.github.com/assets/6665378/2171252/c856a988-957f-11e3-84e2-ea54b6a79261.jpg)

Защо затваряте темата, без да сте направили нищо. Поне отговорете и кажете защо е така ...
