### ISSUE TITLE
[DND]Holiday - Love - AH Bunny Combat Bug

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#196]
http://prikachi.com/images.php?images/879/7059879K.jpg
Благодарение на това, се получава Combat bug, в Orgrimmar.

**Comment by onsgame** [comment]
отдалечи се от "ah" и ще се оправи

**Comment by Attractivee** [comment]
Какви сте вие бе хора, репортвам за да го фикснат...
прекалено спрели хора има в тоя форум

**Comment by FALL1N1** [comment]
Бях в AH-то и това NPC го няма. Може ли някои да потвърди?
