### ISSUE TITLE
i cant login

### ISSUE THREAD

**Issue by uncle2crunk7711** [DragonFire/panda#197]
its juss stays at the authentication when i try to logg. ive made the account and checked my email and verified it and it wont let me logg in. i made a new acount also and did the same thing as far as verification and all and it wont logg in  wat do i do cause i rlly want to play

**Comment by 3DViking** [comment]
Hello,
Which is your account name?

**Comment by muglata** [comment]
hello from me aggain i still cant log in my nick name and acc its muglata hero : Lifestealer :( i see you make some thing but i still cant log in

**Comment by Attractivee** [comment]
Try to add SET realmName "Pandaria" 
in "WTF/config.wtf" on the top of the file.

**Comment by muglata** [comment]
nope mate that its not a problem its just after my bg it some bug after it icant log in but i will try it now :) if it works i will write it here

**Comment by uncle2crunk7711** [comment]
my account name is uncle2crunk7711

**Comment by 3DViking** [comment]
can you try to ping pandaria.dragonfire-bg.net, what results you see?

**Comment by muglata** [comment]
mate i cant log in with my heroe my screen freeze at 90% at the game pls help me mate :(
