### ISSUE TITLE
Проблем при логване

### ISSUE THREAD

**Issue by Roigbg** [DragonFire/panda#200]
Героят се казва Mellice (main hero).Първо имах проблем с ерорите затова цъках с алтовете ми.После играх малко до 82 лвл и преди около 2 седмици се появи проблема с логването.Не може да зареди докрай. Та от тогава си чакам..Триите ачивове ако трябва незнам там ,но моля направете нещо . :)
![wowscrnshot_021314_153513](https://f.cloud.github.com/assets/6537784/2160149/1f662b1c-94b4-11e3-8607-67d0de8bbfb2.jpg)

**Comment by muglata** [comment]
братле аз имам същия проблем но не мисля ,че е от ачовете Nick in game : Lifestealer

**Comment by Roigbg** [comment]
Zashto zatvarqte temata sled kato oshte nemoga da vleza nz... :) Lifestealer vliza ve4e..toi mi e ot guilda no ne toi e otvoril temata a az .Moqt  geroi se kaza    ,, MELLICE".
