### ISSUE TITLE
Проблем при логване

### ISSUE THREAD

**Issue by Llewella** [DragonFire/panda#202]
Името на героя е Freia, при логване с него зарежда до 90% и след това спира. Героя беше мъртъв и както летя за да си взема трупа, паднах от пилето в областта на Mount Hijal , релогнах за да се оправя и до там беше.

**Comment by AnTOLI** [comment]
Opravete i heroto Emisiqq resnete  mu ach ;x

**Comment by Llewella** [comment]
Героя все още не е оправен, защо затваряте темата?!
