### ISSUE TITLE
wut ?

### ISSUE THREAD

**Issue by Roigbg** [DragonFire/panda#205]
https://github.com/DragonFire/panda/issues/200  само ми кажете с каква цел го затваряте след като нищо не е оправено ? Героят ми се казва Mellice и още не мога да влеза а човекът писал коментар по-доло може. Евала !

**Comment by VaHn4oY** [comment]
Явно е на избирателен принцип , на някои хора им оправят героите за ден два , а на други ,които чакаме над 3 седмици , не...
