### ISSUE TITLE
План за решаването на проблемите в сървъра

### ISSUE THREAD

**Issue by Roxolana** [DragonFire/panda#209]
Макар празните приказки да не са моя тога, явно съвсем идеалистично си мисля, че ако ударя едно рамо може нещата да се раздвижат. Съответно, за да избегна неяснотите, ще синтезирам максимално простичко кои са нещата, върху които екипът, работещ по сървъра, следва да концентрира усилията си. От поправките, които засвидетелствам до този момент, съдя, че приоритетите в тази посока са напълно неверни.

[1]. Оправете Achievement-ите на всички герои в сървъра. 

Вярвам, че на абсолютно всеки по-сериозен играч му писна да чака да му резетнете героя. Всекидневно това е основната тема в world. На всичкото отгоре въпросните "оправяния" са напълно малоумно решение - правят се 5 daily-та, получаваш 100 achievement points и отново увисваш пред loading screen-а, псувайки сървъра. Да не говорим за влизане в BG-та.
Не стига това, ами и през цялото време тънем в неведение какво от постигнатото в ДФ ще ни се признае, та аджеба да знаем какво да правим. Работещото от новото съдържание не е много, та да ни държи заети. 
А и за капак на всичко, при всеки "reset" всички Realm First-ове и acvhievement-и от Катаклизъм и Пандария отиват в небитието. Нямам никаква представа за к'ъв хуй оправяте някакви куестове, вместо да адресирате този проблем. Нелепо е. Очеизвадно куестовете са достатъчно, че да се вдигне 90то ниво, така че end-game content би следвало да е акцентът в работата Ви. Което ни води до точка две.

[2]. Оправете Currencies.

Писна ни до гуша да правим daily-та като ненормални и да не получаваме нищо за усилията си освен репутацията. Конкретно аз съм изпълнил минимум хиляда куеста  в Пандария, гарантиращи ми 5к Valor Points. Мистерия тогава как имам само 22. При положение, че е толкова трудно да пуснете рейдове, защо не ни дадете шанса да се "гиърваме" индивидуално? Същото с Justice точките. Същото с Cooking token-ите. В банката си имам 1 чанта с Darkmoon Tokens, дето уж трябваше да се конвертират в currency при смяната на patcha. На wotlk имах 2к frost емблеми, които нито се превърнаха в Justice points, нито в злато, както би следвало. ГАРАНТИРАМ ВИ, че всеки в сървъра е на моето деридже. 

Като резултат от горните две точки, след като си завършим daily-тата в Пандария, по цял ден летим нагоре-надолу като малоумни и се чудим какво да правим. Неслучайно целият сървър вдига Monk-ове - просто няма какво да си правим с основните герои. Така стигаме до точка три.

[3]. Оправете репутациите и пуснете 1 рейд.

Вече изкоментирах липсата на безсмисленото гриндене на куестове, които дават само репутация. Не споменах обаче, че тая репутация до абсолютно нищо не води. Нито можем да си вземем предметите от Quartermaster-ите, понеже струват justice и valor points, нито можем да вдигнем най-смислената от репутациите в Пандария - тази с Шадо-пан. Движейки се по плана, който излагам, абсолютно оптимистично ще предположа, че сте се справили с точка 2 и вече този проблем е частично решен. Остава да оправите Шадо-пан, та да си дават daily-тата и всичко ще е ток и жица.

Вече в малко по-далечно бъдеще, ако се хванете да пуснете един рейд, в който да зациклят вече понапредналите като организация и екипировка играчи хич няма да е лошо. Дори много неща по него да не работят съвсем както трябва самото наличие ще създаде някаква цел и форсмажорът ще спомогне за мотивацията на играчите. 

Живо се надявам, че екипът ще вземе присърце написаното. Очевидно сървърът има и други проблеми, но ако тези не се решат моментално рискувате да го обречете напълно.

Благодаря за отделеното време и съжалявам, че тъй бъбриво.

**Comment by Cherrylolz** [comment]
Regnah se specialno da kaja 4e toq pi4 trqa da go napravite GM, a vie da se grymnete, typaci :) evalata brato

**Comment by leisss** [comment]
strahotni idei ..evala na mom4eto 4e se opitva da pomogne i ne se pritesnqva da spodeli ideite si ... i samo ako moga da dobavq ako moje i da se pusnat 1, 2 Dungeona s16to nqma da e lo6o

**Comment by Neghar** [comment]
Dosta dobri idei,bravo.Nqma da e losho da se slu4at goreizbroenite neshta.Opredeleno nqma kakvo da se pravi na 90lvl i ne samo.. ;s

**Comment by Belissima** [comment]
Подкрепям ги идеите. Сигурно всеки трети си ги мисли тези неща, но не всеки може да обобщи и синтезира по тоя начин. Браво за труда. Бих добавил само и пускането на dungeons преди някой рeйд за да има нормален прогрес без прескачане на съдържание. 
Както и да се фикснат class spells поне на 70-80% на повечето класове иначе сме обречени да наблюдаваме групи от по 3-4 класа (който са най-бъгави за момента), било то за рейдове или battlegrounds.

**Comment by onsgame** [comment]
да така е негхар
знаем те много добре как бъгваш и шотваш играчите в бг та не може да  удряш по 450к на играч просто не е реално :)
подкепям идеите на Roxolana

**Comment by ongamex** [comment]
то не е само тоя а сички warr-ове

**Comment by Ritto** [comment]
Rado GMite triabva da go chetete kato uchebnik, dalech she stignete :D

**Comment by AnTOLI** [comment]
Ostava i taq tema da go closed i si triq MOP ;d

**Comment by Absinthia** [comment]
Едва ли ще обърнат някакво внимание...По добре от сега трий моп...

**Comment by AnTOLI** [comment]
haha

**Comment by 3DViking** [comment]
Здравейте,
Само искам да ви кажа, че не сме спирали работата на оправянето на проблеми и бъгове по сървъра, ще сложим друга версия до няколко дни и ще видите разликите.
За жалост това което сме взели като ядро е много добре от към ядро (спелове, скилове, гулдии и тн), но от към база данни хич не е добре и оправяме всяка зона една по една, това е причината и да не пиша тук. 

Тези които искат да ми помогнат могат да ми пишат на скайп (ribkii), като ме добавяте си напишете ingame char-a, иначе няма да ви добавя.

Ще ви дам достъп до тестовия сървър, акаунт с права и ще ви кажа какво можете да ми помогнете.

Също така работим по сайта, потребители които ги направим модератори да могат да отбелязват всеки quest, item, creature, object и тн. колко процента работи.
