### ISSUE TITLE
Вие живи ли сте правите ли нещо по тоя сървръ?

### ISSUE THREAD

**Issue by Kriviqotprede** [DragonFire/panda#216]
Я влезте ги погледнете тия Astel,Viketo,Ivelinabg,Ancaytone и да не изреждам другите какви тъпотии правят...
Просто на приеста му махнете глупавия inner fire , на хънтера snake trap-а а тоя Ivelinabg може и героя да му изтриете направо...

**Comment by Davieba** [comment]
Аз имам по- добра идея към ГМ! Да спрете направо всички спелове  и да се бием на AUTO ATTACK всички класове!!!!   Яко е нали ?   :dancer:

**Comment by Kriviqotprede** [comment]
Благодаря на Готик !!

**Comment by marto0oo** [comment]
Вие като сте хорди ви е лесно аи на вас да ви изтрият Dreamlord,Neghar,Torrona i drugite buggavi izpalneniq Edyy а ? Гледаите първо вие кво праите после нас? В началото никои не използваше бъгговете,вие почнахте е па няма да ви стоим да ни шотвате я първо да орпавят сървъра и тогава се оплаквай!!! Аз ко да кайа за маговете като не бият да сега да използвам хакове,че да ва бия!!!Отделно знам магове дет и бъггват с талантите ама и дума не сам акзал нали и хорди и аллита !!! Така,че гледайте първо вие кво праите,лесно е в другата паница.

**Comment by Neghar** [comment]
Dosta bezmisleni temi v toq github.Ne razbrahte li che tova e test realm.Oznachava che SPELOVETE i mnogo drugi neshta sa BUGAVI.S teq reporti se ulqhte.Po vashta logika trqbva da iztriqt vseki Warrior,Hunter,Paladin,Warlock,Priest<Rogue? Teq spelove she se opraqt reportnato e vsichko bugavo,lichno az reportnah tupiq warr bug i dori nemojeme da razbereme ot kakvo se polu4ava.Taka che zapazete si toq HATE nenujen za vas.I dvete frakcii sa praili gluposti ne e vinoven samo edin.Horata mi zvunqt i po tela da me psuvat zaradi nekfo pvp.Stegnete se malko.

**Comment by onsgame** [comment]
стегни се ти и престани да бъгваш Негхар :)
