### ISSUE TITLE
ако това е вярно... нямаше да има проблем с дигането до 90 лвл?

### ISSUE THREAD

**Issue by Mympa** [DragonFire/panda#222]
Mount Hyjal   85 % Quests working.... по ачивмент са 115 куеста
явно бачкат по малко от 85 % защото може да дигнеш само половин лвл 
и така на 80  лвл трябва да идеш Деепхолме където   85 % Quests working
и там по ачивмент има 110 куеста и оттам половин лвл ..ставаш 81 лвл и поради факта че няма работещи куестове и инстанции отиваш къде? на 81 лвл отиваме Улдум(земя за 83 лвл )където по ачивмент са 110 куеста и 95% Quests working.Тук ако се помъчиш може и 2 лвл- да дигнеш защото земята е за по голям лвл и дава повече експ..така че може да станеш 83 лвл .Така стигаме до Туилайт където по принцип е за 84-85 лвл и има 95 куеста а според ДФ 90% Quests working и така дигаме 84 лвл и примерно 50% от 85 лвл , но да не забравяме че все пак тези данни от сайта на ДФ меко казано не са верни. затова предлагам хората които отговарят за фиксването на куестовете да сложат някъде на сайта или форума РЪКОВОДСТВО ЗА ВДИГАНЕ НА ГЕРОИ ОТ 80 ДО 90 ЛВЛ ПО СТАНДАРТА НА ДРАГОН ФИРЕ,защото всички знаем че ДФ е различен от останалите близлайк сървъри!
но все пак искам да питам дали работят куестовете в Молтен Фронт!! това е земя за 85 лвл(преди МоП) , фаерландс се намира там и има поне 15 дайлита ( или е като преди в ДФ дайлитата не дават експ)
А и доколкото съм запознат в БГ-тата също трябва да дава експ.
И когато удариш заветния 85 лвл трябва да идеш в Огримар или Стормуинд и да вземеш куеста си за Джаде форест, където на близард 1 куест дава към 200к експ (тук трябва да дава към 600к ) и ако е верен факта че 85 % от куестовете работят  би трябвало да се дигнат 86 лвл и половината от 87 но уви стигаме само до 86 лвл ( и то с клизма). в края по един или друг начин ставаш 90 лвл , заветният 90 лвл и си блъскаш сега главата какво да правиш: да играеш пвп или да се мъчиш да дигаш репутации и да слагаш някакъв епичен гиър. И какво разбираме: не работи РДФ-то и двата райда за този пач. Могу Шан и Хеард оф Феар!
АКо си тайлор трябва задължително да дигаш репутации към аугуст целестиалс, шадо пан за да може да си купиш енчантите за оръжия и 28 слотовата торба.Както чета по форумите това е проблем след като не работят дайлитата(или поне повечето),защото виждаш ли те не дават Валор-и.ЕМи няма логика да не дават но не прочетох някъде някой да каже защо не дават и кога ще започнат да дават. да не говорим за райдване или рдф, след като на мен (80 лвл ) ми излизат когато натисна И-то всички инстанции за всички лвл-и (даже и 90 лвл хероиците),Продължавам да настоявам да се сложат теми някъде по страницата или някъде в форумите и да се каже на играчите какво работи и какво не защото извинявайте 85% от куестовете работят..(така пише в сайта),ама кои са, къде са икога ще работят останалите не се знае!!!Направете го лесно и удобно как да си дигнем примерно дадена репутация (без да се налага да биеш мобове като гламав за Голден Лотус репутацията)

жалко че не можете да се насладите на играта като цяло , има много интересни неща, надявам се да се фикснат скоро, за да можете да райдвате, да пражите challenge mode dungeoni (откъдето може да вземете 4 маунта+ специфичен клас сет за трансмог). Да започнете да зе мъчите за легендарния куест за legendary back (IL 608),който  се вади за около 3 месеца (ако имаш късмет за 2 и половина)
но за тази цел трябва да има РАБОТЕЩИ ИНСТАНЦИИ И РАЙДОВЕ,защото зная че има добри гилдии на ДФ и ще има конкуренция за реалм фирст ...(ама то сега и тези ачивменти не бачкат). МНого се надявам да се пооправи малко сървъра. И айде да не се нареждаме за това че аз съм хорда а другия е алиансе,нека заедно да помогнем да се оправят проблемните неща.

**Comment by ongamex** [comment]
"Mount Hyjal 85 % Quests working.... по ачивмент са 115 куеста
явно бачкат по малко от 85 % защото може да дигнеш само половин лвл "

Секвартиранта дигна левел и половина, вероятно може и още.

**Comment by opalq** [comment]
Единствения проблем, който съм имал е вдигането от 88 до 89. Друг е въпросът, че на 90 лв няма какво да се прави- нито професии могат да се вдигат, нито райдове, нито нормално bg ( всички класове са изключително бъгави). Т.е в сегашното си състояние сървърът не става за нормална игра. Това трябваше да е тест сървър за няколко месеца, и след това да се пусне

**Comment by marto0oo** [comment]
Така в Моунт Хижал дигнах 2 лвл аз,чисто 2,Деепфолм дигнах 1 лвл и половина почти,Улдум 1 лвл и 20 %,85 лвл дигнах в Хидландс почти ез проблем,Панда най-мачителное от 88 лвл до 89 лвл последните 10 или 20 % са най-хард.Daily-тата дават ехп.Рдф на ката има няколко работещи имам ачове.спрямо ехп-то трябва да е като близз 200к ехп да си е 200к,някои казват,че е х2 сървърът,дефакто е х2 трябва да е 400к ехп а,не 600к както ти казваш.Спрямо 90 лвл да няма нищо какво да правиш,чакаме update-и.Това е за сега,друго ако си сакат с куестите и незнаеш как се минават,има youtube ако не ти е нещо ясно и си ти.Само едно нещо си прав,спрямо % на зоните на ката не са истинските проценти,панда се доближават,кам това,което е писано :)

**Comment by Mympa** [comment]
пич играя на близард имам 5 героя 90 лвл ..много добре знам за какво иде реч, на ДФ съм може би от 7 год (без последните 2)., така че .. знам за сървъра, просто ми е интересно като влизам в играта и се пише в world канала че има маса неработещи куестове! Аз пуснах една тема за един куест (легвндарен ) който продължава до пач 5.4 ..ама явно не им се заминава да направят тази част от него,която е за този пач. 
http://eu.battle.net/wow/en/character/emeriss/Mympa/advanced
http://eu.battle.net/wow/en/character/magtheridon/Apucmokpamka/advanced
http://eu.battle.net/wow/en/character/emeriss/Apucmokpamka/advanced
http://eu.battle.net/wow/en/character/magtheridon/Mympeca/advanced

**Comment by marto0oo** [comment]
Сървъра е едва от 3 седмици ако очаквате пък легендарните епични куести да бачкат нещо си се обаркал,другото,което и аз съм цакал близз,не е важно колко дълго цъкаш,а дали можеш,не е важно колко херота имаш,можеш ли да ги играеш!!!Щот ако излезеш срещу про от близз си мъртав на 5 сек маж 20 сек.Има много нообове и в близз,това,че си казал,че цъкаш близз не е кой знае кво,важно е можеш ли щот хора от близз дошли на панда сега,които цъкат ги праскам на дуел!!! Така че близз има всякви.Радвам се,че имаш положително мнение за сървъра,аз лично вярвам,че ще стане The Best Панда пиратски сървър.Вярно е избързаха с изкарването му,щот дигнеш ли 90 лвл и си до там,но след едно неопределено време,ще стане як сървър!!! Продължавай с репортите,което видиш,че не е правилно,но се ограничи в това: Wowhead,как бачка или не бачка в ДФ,ако си го играл,точно какво трябва да прави. :) Успех ;)

**Comment by Absinthia** [comment]
DF никога няма да стане The Best Панда пиратски сървар...Понеже ГМ-тата са мързели :)
