### ISSUE TITLE
Clemency

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#224]
Ако имаме този талант и натиснем alt + f4( бързо излизане от играта ), таланта се бъгва и можем да пускаме  hand of prot, hand of freedom, hand of sacrifice, hand of salvation колкото си искаме, без Cooldown.
http://www.wowhead.com/spell=105622

**Comment by marto0oo** [comment]
на моя паладин без  алт+Ф4 се получитова,някакъв бъг в таланта е.Което е много тъпо спрямо другите играчи,а запалитата е яко.Вече е ропортнат този Талант :)
