### ISSUE TITLE
Demonmasster bugged again ! 

### ISSUE THREAD

**Issue by Demonmasster** [DragonFire/panda#228]
След последното си логване повече не ми се получава номера . Не мога да логвам , Забива ми на около 90 % лоудинг скрийна и дотам . Последните постижения , които взех бяха стандартните за 3:0 в Уорсонг гулч и единична победа (или беше за под 6 минути) нещо от сорта . Помагайте !

**Comment by Demonmasster** [comment]
10-ти ден чакам какво се случва подяволите ?

**Comment by Min4AKK** [comment]
Сега се занимават с правенето на 5.0.5 сървъра и едва ли някой ще те отрази

**Comment by Demonmasster** [comment]
НЕ знам  сървър ли правят каква точно е причината , но по тоя начин няма да задържат и 70-тината заблудени останали играча ...
