### ISSUE TITLE
Проблем с герой!!!

### ISSUE THREAD

**Issue by Eclipsftw** [DragonFire/panda#237]
Пиша Ви за 3 път , тъй като няма никакво развитие по оправянето на героя ми - Eclipsftw , както Ви писах в другите теми чакам от месец (още в началото ,когато пуснаха сървъра играх 2 дни и толкова..).Героят забива на loading screen  на около 90% .Ще ми го оправите ли да мога да влизам с него ? и как може на дадени играчи да им оправяте героите за ден-два , визирам играча Kozelbg (нищо лично към него) както и много други ..Масово играчи от аlly страната не могат да влизат с героите си , то наистина заприлича на хордски сървър..

**Comment by onsgame** [comment]
Еклипсе не си хорде за това няма да ти оправят проблема .. или ще отнеме доста време докато го оправят но уви при хордите става много по бързо 
поглени предишната статия за забиване на героя на козелбг на него гм-та оправиха проблема доста бързо :)

**Comment by Pichaga1997** [comment]
Kakva e logikata che pri hordite stava po-burzo (i az imam takiva nabliudeniq,ama zashto :D)

**Comment by Roigbg** [comment]
Ами странна работа..Както героите им оправят по-бързо ,така и не случайно примерно имат костенурката във вендора на пандите в столицата а алитата не ,или пък другото нещо са хонор вендорите в SW които липсват а в Orgrimar са си на мястото :)

**Comment by Pichaga1997** [comment]
Nqkoi znae li koga shte minavame 5.0.5 (s nadejdata togava da oburnat malko poveche vnimanie na allianca)

**Comment by gghost** [comment]
Добър ден и от мен! Eclipsftw, моят герой е хорде и има същия проблем, тъй че не оставай с погрешното впечатление, че това оказва влияние на иначе да -ИЗБИРАТЕЛНОТО  отнощение кой герой да отблокират. . В този ред на мисли , поводът да изразя своето становище тук е факта, че като всички Вас и аз съм един обикновен редови играч, който има желание за игра и развитие. Старая се да влизам в положението на хората, които имат желание да оправят сървъра и работят усърдно по въпроса, но защо Вие уважаеми GM, не проявите елементарно разбиране и към нас-,,простолюдието,,, което с надежда чака да обърнете внимание на тикетите, с които Ви молим да решите толкова елементарния проблем -да ни пуснете да играем?Нима е толкова трудно и непосилно за вас да драснете два реда , с които поне да ни уведомите , че нямате възможносста да ни отблокирате героите, било то ingame., било тук или пък в сайта.....Всички сме наясно, че има технически проблеми и че се опитвате да ги решите, но нима факта, че ние не можем да играем и се обръщаме към Вас с молба за помощ или поне отговор не е проблем, имайте доблестта поне да ни информирате има ли смисъл да пробваме и да се надяваме скоро да можем да играем с героите си! Като заключение , се обръщам към Вас с молба да акцентирате вниманието си върху ХОРАТА, които имат желание да играят , не ни игнорирайте-нас и проблемите ни  и ние ще проявим съответното разбиране, защото иначе ще имате сървър, но няма да имате играчи в него. Нека има нормална комуникация помежду ни! Не ни дръжте в неведение!Благодаря ви!

**Comment by Min4AKK** [comment]
Vsichko e s vruzki cqlata rabota.Ako ne te poznavat kolkoto i ticketi i oplakvaniq da podadesh,nqma da promenish nishto.Tova e naglasata i predstavata za bulgarina.

**Comment by Mympa** [comment]
още от едно време беше така !!! как мислите се взема achievment The Loremaster на ДФ ако не с връзки !!! айде да си гледат работата ГМ-тата за да не останат както се каза по горе само със сървър без играчи!! и е редно да се обзлужват еднакво бързо и двете фракции или ако не могат да пишат че не могат ... ама те май и да пишат не могат !! и игра не могат да подкарат.. а за 5.0.5 ... да не мислите че ще е по добре ... те тази не могат да оправят ... вие за следваща искате !!! ако питате мен най добре е 5.4.3 да се сложи направо и да оттам да се започне РЕШАВАНЕТО НА ПРОБЛЕМИТЕ!!! Ама като знам ... колко са бързи нашите ГМ-та по добре да си оправят там проблемите на WoTLK реалма и да си седят там

**Comment by Min4AKK** [comment]
Loremaster moje da se vzeme i bez vruzki (makar i dosta trudno :d).Inache trqbva da se stepenuvat neshtata po vajnost-spored men trqbva purvo da se opravqt vsichki bugnati,iztriti,nedorazviti geroi i togava da osvedomqt vuv FB ili v saita che na edi koq si data zapochva prehvurlqne na danni i geroi v drug server,v koito edi kvo si,edi shto si,tui kato tozi e bil proben,no ima mnogo neshta,koito ne rabotqt (primerno) i za da ne otneme mnogo vreme da gi opravqme,shte pusnem 5.0.5:za koito se tvurdi che vsichko raboti normalno,ne znam kak stava tova ne sum tolkova navutre s tezi neshta :d 
I sled kato napishat tova,na posochenata data (ako se nalaga zatvarqt MOP servera za izvestno vreme) i zapochvat da se zanimavat s drugiq

**Comment by Mympa** [comment]
и искам да запитам как ще постигнеш нещо по - различно от общоустановеното, КАТО НЯМА АКТИВНИ РАЙДОВЕ(НЯМА И ДА ИМА СКОРО),НЯМА РДФ, НЯМА ЛФР, НЯМА ДАЙЛИ КУЕСТОВЕ,(ИМА АМА .. НЕ ДАВАЛО ВАЛОРИ,ЗНАЧИ НЯМА), СИГЪРНОИ ВАЛОР ВЕНДОРИТЕ ГИ НЯМА.. Още има проблем с куестовете на малък лвл, което спира нови хора да играят !За мен този сървър е боза и загуба на време да се играе на него !!

**Comment by Pichaga1997** [comment]
Остави тея глупости от 2 седмици чакам да ми оправят героя и не съм видял резултат нито отговор от някого
