### ISSUE TITLE
Тежък проблем с Героя!

### ISSUE THREAD

**Issue by Pichaga1997** [DragonFire/panda#238]
Не разбрах дали може да бъде възстановен съответния герой Lengsalau Level 63 Pandaren Monk Alliance.Писах тикет тук,в играта и в Helpdesk с малко повече детайли за него,не знам дали там влиза вече някой,но никъде не получих отговор.Ще съм ви много благодарен ако намерите възможност и време за него.

**Comment by onsgame** [comment]
еми сигурно не може да се въстанови  :(

**Comment by Pichaga1997** [comment]
аз не знам дали са го прочели

**Comment by Pichaga1997** [comment]
гледам и други се оплакват за нещо по-просто като оправяне на ачивмънти така че съм по-склонен да вярвам че сега се занимават само с 5.0.5 сървъра и временно не обръщат внимание на проблемните герои

**Comment by StDarkAngel** [comment]
Възстановяването работи над 70-ти левел.
