### ISSUE TITLE
ПИСАНО ОТ СЪРЦЕ

### ISSUE THREAD

**Issue by Pichaga1997** [DragonFire/panda#241]
Уважаеми,ГМи!.
МОЛЯ ВИ!Вярно е,че сте заети в момента с обработката на сървъра и оправяне на всякакви бъгове,но още никой не ми е върнал героя - Lengsalau 63lvl Pandaren Monk (Alliance) Той не е 80lvl или с проблемни achievments(лесен за оправяне),но беше сред първите панди в сървъра и имам много добри спомени оттогава и самият герой има голямо и стойностно значение за мен.
ЕТО И КАК ИЗГЛЕЖДАШЕ:
http://s15.postimg.org/4zjbckk63/Wo_WScrn_Shot_013114_162440.jpg
http://s15.postimg.org/wyi2h6b6j/Wo_WScrn_Shot_013114_162840.jpg
http://s27.postimg.org/nzmxv1jnn/Wo_WScrn_Shot_013114_162828.jpg
accounta e " ..."
emaila e "..."
nomera za prashtane na SMSi " ... "
Беше изтрит миналия месец около 1-2 февруари.Стой изтрит оттогава,а тикетите които пусках-неотговорени от 2 седмици.Последното място,в което съм бил с него е Zangarmarsh Outland.Допълнителна информация-беше в гилда True Damage.Има двата бъфа от куестовете на дърветата в Zangarmarsh.Има Staff от награда за куестовете в Zangarmarsh и повечето итеми са му от там.
Моля пишете ми на  potrebitel_klient@abv.bg :) за повече информация (писал съм и в Helpdesk няколко тикета)

**Comment by Bleedeyes** [comment]
И аз чакам все още чакам да откликнат на молбата ми и да ми върнат мейн героя...
Да не говорим че в акаунта на един приятел има три бъгнати героя 80 левел от които единия зарежда на 90% а другите два ерорват 3 сек. след като логнеш с тях и не съм ги репортвал умишлено, за да не натоварвам екипа :)

**Comment by Min4AKK** [comment]
Te sq se zanimavat s drugiq server,ama trqq gi vurnat predi otvarqneto mu shtoto tam nqma da gi ima v baza danni

**Comment by Min4AKK** [comment]
I tam nqma da mogat da gi vurnat
