### ISSUE TITLE
Поредният бъгнат герой

### ISSUE THREAD

**Issue by valer4o** [DragonFire/panda#245]
Зарежда играта на 90%, героят е "Poo".  вече 20+ дена, моля за помощ

**Comment by Min4AKK** [comment]
Ne si samo ti,az sushto chakam ot dosta vreme.ama... .Takiva kato Kozelbg i Enragelol bqha bugnati samo 2 dena i gi opraviha.ama te poneje nali sa vruzkari i mn qsno che shte gi opravqt...
