### ISSUE TITLE
Настъпи раздвижване в сървъра !

### ISSUE THREAD

**Issue by Demonmasster** [DragonFire/panda#246]
Смятам с това заглавие има някакъв макар и минимален шанс за привличане на нечие внимание . 
Един чисто приятелски съвет от мен към всички от екипа на ДФ . С НЕоправяне и НЕпомагане на нуждаещите се играчи не печелите позитиви , нито нови играчи . точно обратното - и тези , които по една или друга причина все още играят спират , заради невъзможност за игра в главен / любим герой . Всички разбират работата по новия проект , но пренебрегването на нуждите на играчи в сървъра не спомагат за популяризирането му. 
Давам пример - играч , на когото не му се откликва дни наред на молбата за фиксиране на керъктър в акаунта , бива запитан от познат " искам да почна да цъкам в някой неплатен сървър , дай някакъв съвет ?" , еми нормално е отговорът да му е " всеки , ама не и ДФ " .
С най - добри чувства :) Успех с поправката на сървъра , по който работите .

**Comment by Bleedeyes** [comment]
Не е проблема в това че не се помага... ясно е че на този етап има къде къде по важни неща за оправяне... проблема е че нищо не се казва на играчите, ние искаме ИНФОРМАЦИЯ просто, по какво се работи, кога ще бъде пуснат новия реалм, ще могат ли да се оправят героите и кога ? Просто невежеството и чакането кара хората да се отказват и УБИВА СЪРВЪРА... за това се стигна до тук. От 6 години играя в сървъра и до сега няма кой да ти каже КАКВО СЕ СЛУЧВА в момента ? Преди поне имаше "realm status" и чат пат се сещаха да напишат нещо в него и live chat имаше даже...ИНФОРМАЦИЯТА Е ВСИЧКО. Нямам какво повече да кажа. Успех на всички и не губете надежда, винаги може да е по-зле :dancers:

**Comment by Mympa** [comment]
на сайта има реалм статус .... даже когато е офлайне ..статуса казва че е онлайн... иначе момчетата и момичетата са прави ...никъде няма информация по какво се работи ... как се работи .. сложили някакъв скайп в ФБ и това е ... Ей ГМ-тата и хората които работят по сървъра са се земат в ръце или да кажат че не могат и всеки да си търси друга занимавка,, аз както чета само тук ,.. хората на 90 лвл май нямат какво да правят освен пвп ( и то може би)...а на този пач има много ама много забавление и за хордата и за алианса... Надявам се да оправят и Пандите (монковете де) за да видите как слагат и как не им се мре на райд и пвп.И като казах райд се сетих.. пуснете РДФ-то колкото можете за да видет хората с какво ще се сблъскат!!.И работете си както искате .. (бавно или бързо ) , но повечето хора спират да играят и да се ядосват от бъгнати таланти....куестове ачийвменти Баттле грануди, да не говорим за инстанции и райдове и валор точките ... :) айде успех ви пожелавам !

**Comment by valer4o** [comment]
...... "Не е проблема в това че не се помага... ясно е че на този етап има къде къде по важни неща за оправяне." баце кое е по-важно от играчите в сървара. Точно те правят играта. Аз ако искам RPG ще си разцъквам друга игра. И тая цигания толкова много дни(при мен са повече от 20) много хора да не могат да си играят с геройте е безумие. Няма инфо което допълнително нагнетява напрежение, допълнително се изпускат и губят ползи, а да не говорим че някои "връзкари" ги оправят максимум за ден. Всички тези неща дразнят обикновеният играч, и не виждам нещо да се прави което да ме опровергае.
