### ISSUE TITLE
Още един герой който не може да логне.

### ISSUE THREAD

**Issue by ongamex** [DragonFire/panda#247]
Imoogi не може да логне.

**Comment by Min4AKK** [comment]
Shto

**Comment by ongamex** [comment]
Стандартното, заради ъчивмънтите.

**Comment by Min4AKK** [comment]
Ama tva ot licha li oshte ne sa ti bili resetnati ili novi

**Comment by ongamex** [comment]
нови ъчивмънти везех, Послено май беше за разкрита земя мисля че.
