### ISSUE TITLE
Opravete geroq Fakyou

### ISSUE THREAD

**Issue by Proof9011** [DragonFire/panda#248]
mom4eta aide be 4ti den nemoga da logna znam 4e burzate da patchnete ama opravqite geroite da mojeme da igraeme mejduvremenno ...

**Comment by Min4AKK** [comment]
Недей да се оплакваш аз чакам половин месец и още не са ми оправили моя,не си само ти

**Comment by Attractivee** [comment]
Още една тема пусни
