### ISSUE TITLE
20 Дни

### ISSUE THREAD

**Issue by Pichaga1997** [DragonFire/panda#249]
Уважаеми,ГМи!.
МОЛЯ ВИ!Вярно е,че сте заети в момента с обработката на сървъра и оправяне на всякакви бъгове,но още никой не ми е върнал героя - Lengsalau 63lvl Pandaren Monk (Alliance) Той не е 80lvl или с проблемни achievments(лесен за оправяне),но беше сред първите панди в сървъра и имам много добри спомени оттогава и самият герой има голямо и стойностно значение за мен.
ЕТО И КАК ИЗГЛЕЖДАШЕ:
http://s15.postimg.org/4zjbckk63/Wo_WScrn_Shot_013114_162440.jpg
http://s15.postimg.org/wyi2h6b6j/Wo_WScrn_Shot_013114_162840.jpg
http://s27.postimg.org/nzmxv1jnn/Wo_WScrn_Shot_013114_162828.jpg
accounta e " ..."
emaila e "..."
nomera za prashtane na SMSi " ... "
Беше изтрит миналия месец около 1-2 февруари.Стой изтрит оттогава,а тикетите които пусках-неотговорени от 2 седмици.Последното място,в което съм бил с него е Zangarmarsh Outland.Допълнителна информация-беше в гилда True Damage.Има двата бъфа от куестовете на дърветата в Zangarmarsh.Има Staff от награда за куестовете в Zangarmarsh и повечето итеми са му от там.
Моля пишете ми на potrebitel_klient@abv.bg :) за повече информация (писал съм и в Helpdesk няколко тикета)

**Comment by onsgame** [comment]
по колко пъти ще пускаш тази тема не разбра ли че няма да ти върнат героя ?!

**Comment by DarkAngel39** [comment]
Така ли не разбрахте, че github не е място за реване, а за докладване на бъгове по играта? Девелоперите да тръгнат да ровят из backup на базата данни (ако има такъв), да ти върат героя ли? С това трябва да се занимават други хора, които изобщо може да не гледат тикетите тук. Пиши на support@dragonfire-bg.net, както си е казано в http://guildszone.com/contactus.

**Comment by Pichaga1997** [comment]
Писал съм няколко от 3 седмици които са без отговор а  от скоро не мога да вляза,стой на Authentication Required

**Comment by StDarkAngel** [comment]
Не могат да ти върнат герой 65 левел след като е изтрит от играта веднъж.
