### ISSUE TITLE
Quest:  [83] [Premature Explosionation](Part 2 of 2)

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#25]
http://www.youtube.com/watch?v=yMESKAu74-s
NPC-тата не са едно върху друго и съответно неможеш да ги събориш.

**Comment by 3DViking** [comment]
видеото е нещо грешно

**Comment by Attractivee** [comment]
http://www.wowhead.com/quest=28250#.
Мисля, че е точно така :\
Quest item-а ( чука с който ги удряш ) си го има, просто не са една върху друга, маймуните :D
