### ISSUE TITLE
Тъпотия до шия

### ISSUE THREAD

**Issue by Neghar** [DragonFire/panda#251]
Правите всичко възможно май ако въобще някой обръща внимание на тези репорти да изгоните и най старите играчи които са напълно против местенето в друг сървър.Тези които пишете репорти ще ви посъветвам да не се хабите.Резултата е един и същ (нищо).Спестете си малко от времето като не си го губите с тази конкретна задача.Честно  казано ГМ-тата  ще е много по добре просто да кажете направо че не го гледате този github просто за да знаят останалите хора.И на вас ще си направите услуга и на нас.Сървъра е с голяма репутация но уви тя е в миналото.Никога няма да бъде по старо му.Само едно немога да разбера като се прави нещо по сървъра толкова ли е трудно един Changelog или въобще просто да напишете две изречения че става нещо.Титла мога да ви връча за най-несериозния екип в който и да е сървър по света дори и във фънките има по сериозни админи и въобще стафа.Очаквам се нетърпение коментари от типа "ако не ти изнася се махай" но това не се отнася за играчите а ми за екипа им затова спестете ги.Въпреки че се съмнявам някой с някакви права да го прочете камо ли да си вземат някаква забележка но така или иначе ако всички си изразиме недоволството е по вероятно нещо да стане.

**Comment by DarkAngel39** [comment]
По сървъра се работи, просто девовете са малко, а проблемите по 5.0.5 ядрото са много. Няма кой да тръгне да пише changelog за всеки оправен куест (а куестите са основния проблем). End game content е сравнително добре от към pve и pvp, също така и магиите на героите са доста добре. Pроблема е, че засега няма как малките нива да вдигнат. Т.е. трябва да се прегледат и оправят всички зони от ниво 1 до 90, понеже ядрото е ъпгрейднато от Trinity 4.3.4, където почти всички куест скриптове бяха за 3.3.5 и в голямата си част не са пипнати от тогава. Или казано по друг начин, трябва да се оправят куестите за 2 експанжъна наведнъж. Поради тази причина няма обновления и видима активност, но се работи.

**Comment by Bleedeyes** [comment]
Важното е че се работи явно.... колкото и да не ни се вярва.

**Comment by Thars** [comment]
DarkAngel, хората се махнаха, защото никой не им казваше какво се пипа по сървъра, ако нещо въобще. А и най-големият ви провал беше, когато започнахте да обещавате Катаклизъм и така 2 години. После уж октомври, накрая януари. Слабото ви място е, че не умеете да поддържате контакт с хората, както и не можете да преценявате кое колко би отнело във времето. (А и граматическите умения на хората от екипа ви ни карат постоянно да се замисляме дали си имаме всъщност работа с 13-годишни.)

**Comment by DarkAngel39** [comment]
"Ви"? Не съм нито ГМ, нито девелопер. По едното време помагах за скриптове и т.н., но с 5.0.5 не мога да съм полезен, понеже щайгата ми не може да build ядрото.

**Comment by Powerr** [comment]
Вижте сега момчета : Обръщам се към тези които имат общо със управлението на сървъра , понеже няма никакъв друг начин да се свържеш с "денонощно работещия екип на Драгон Файър" . Останаха в този реалм по малко от 20 4овека и аз съм в това число може би сме невероятни фенове на сървъра или сме пълни дебили и аз вече немога да си отговоря, но да оставим хвалбите настрана. Кажете какво трябва да се случи за да си подберете стабилен екип от хора който да е поне малко приличащ на някои от другите Привейт Сървари. Имате нужда от финанси ли , няма желаещи да се включат или каквото и да е там има много причини , нека да бъде казана каква е . Преди години имаше нужда за закупуването на нова машина доста хора помогнаха , сега ако е такъв проблема(финансов) нека да бъде споделен мисля ,че доста хора биха помогнали поне тези които останаха да логват със сигурност .  Имате някакъв Тест реалм на който се тества , аз самия съм помогнал в началото(с тестването на една от пандарските зони) след което нищо , предложих помоща си каквато и да е тя и всеки друг който все още следи за случващото се в Съвъра  би го направил. Не забравяйте , че сървъра се крепи на играчите в него след като ги изгубите ... нататък е ясно .

**Comment by Neghar** [comment]
Powerr колкото и да ни се иска те не си вземат сървъра насериозно попитаха за помощ-ок.Влизахме след това за още неща като професии  и така нататък 0 лвл няма права.2 репорта в скайп седят със супер много бъгове и не боговолят да влезнат да  го приемат (10 дни).Търпението явно ни е доста голямо..но не сам сигурен колко още ще се задържиме тук.Така или иначе умеят да изполват фрази от сорта на "съпорт 24/7" 1к онлайн и  само ни карат да таиме надежда че сървъра ще се оправи обаче както всички виждаме това нещо не се случва.Доста негативни неща като цяло но нямам си на да идея кое е позитивното.

**Comment by imbaskill** [comment]
А искам да питам понеже с 1 фр ползвахме непозволено макро за голд защо банват перма,вместо да делнат голда с 1-2 седмици бан и най-вече ЗАЩО БАНВАТ И АЦЦ-ТА КОИТО НЯМАТ ОБЩО С НАШИТЕ ДЕЙСТВА И ПО НИКАКЪВ НАЧИН НЕ СА ОБЛАГОДЕТЕЛСТВАНИ ПО ТОЗИ НАЧИН?!?!?!?

**Comment by marto0oo** [comment]
аз имам друг въпрос.Той е следнич: Защо не пуснете пач 5.4.2? много спеллове,куести и пве контент работят,както и пвп и бгта.Защо го казвам: Понеже играя в един руски сървър на него пач и забелязах разликата мейду 5.0.5,5.1.0 и 5.4.2 по работещи неща.5.4.2 бие всичко.вапреки,че спрчмо дмг там е по малко от на 5.0.5 и 5.1.0,но пак е сравнително голям :) Предлагам да работите върху него пач,Близз са на 5.4.7 така че Успех :) Дано се  вслушате в съвета ми :)

**Comment by Mympa** [comment]
четох четох и ме заболя главата... какво очаквате от фрее сървър!! 100% близлайк? Близард са на 5.4.7 и е супер там... руските сървъри са най добрите пиратки в европа... знам го от личен опит. Но тук проблема че няма как са сложат 5.4.2 ... след като не могат да оправят стартовите зони за малък левел... и на 5.4 .2 ще е така.. и не мисля че като пуснат 5.4.2 ще цъфнат и ще вържат!Ще бъде същата работа! Искам да питам какво правят 90 лвл героите без пвп наклонности? Изпълняват ли дайлита, дигат ли репутации, професии, като знам че енчантера прави weapon enchanti,а тайлора 28 слотова торба, която на близард е 3-5К голд.Да не говорим за яките райдове, challenge mode инстанции! Незнам ако приоритет на ГМ-тата са големите левели ... би трябвало да ги има тези неща вече. бях сложил пост за легендарната куест линия на Пандария, но резултат нула, и както се казва ако се пусне 542 пача .. идват нови неща, за които пак ще ревете идват 2 нови боса... идва Throne of the Thunder(райд с 12+1 боса, демек тиер 15), а там босовете са меко казано схема, ако объркаш нещо следва вайп на райда. Онзиден Близард пуснаха Siege of Orgremar X-realm Normal + Heroic 10/25 man..и стана лудница отново:) аз лично имам прогрес там 14/14 нормал Siege of Orgremar и сега се боря за хероик! Руските сървъри са към 85% ако не и повече blizzlike (ама реален, не написан по сайтовете, и експа е малко по малък (ако на близард е 1% там е 3 или 4 (ама реални,защото тук като пише че е 3 значи е 30% ) Как е въпроса с гилдиите, гилд банките, хеирлоомите(итемите които дават 55% екп повече, като 3 итема се купуват само с гилд перутация реверед и някои гилд постижения) незнам .. имам много за писане ама сега нямам време... лично мнение..който иска да играе нормално да ходи на руски сервери :) ако не може или не иска да играе на близард.. A ЗАБРАВИХ ДА ПОПИТАМ НЕЩО НЕЗНАЧИТЕЛНО... ТРАНСМОГ-А  И РЕФОРДЖЕ БАЧКАТ ЛИ ? ЩОТО АКО НЕ БАЧКА РЕФОРДЖЕ ... СЛЕДВА ДРУГИЯ ВЪПРОС: ЗАЩО ПОДЯВОЛИТЕ ИГРАЕТЕ НА ТОЗИ СЪРВЪР? ПРОЧЕТЕТЕ МАЛКО ЗА РЕФОРДЖЕ И ЩЕ МЕ РАЗБЕРЕТЕ ( И АКО БАЧКА, ВИЖТЕ ДАЛИ СИ РАБОТИ НОРМАЛНО ИЛИ Е САМО ЗАБЛУДА)

**Comment by Attractivee** [comment]
marto0oo и Mympa с ИЗВИНЕНИЕ към екипа на проекта ще кажа, че вие сте тоталните спрялаци, обесете се някъде в гората ...

**Comment by marto0oo** [comment]
Обясни защо?2ро Споделям нещо,което много ще помогне за сървъра!!!Да се надяваме скоро да го оправят сървъра и ща вида колко си добър,ако искаш и ще те играя и с най-слабите итеми :Д Споделяме Опит,който повечето играчи тук НЯМАТ,които бъггват и се мислят за голямата работа,иначе са гола вода,както и в 1в1 много се насират всички(най-вече хордите и шорлд и бг 1в1 насират,дойдели още 1 опа се прачт на много добри и ти спамят колко си слаб хаха Вие сте такива) ългарина обича да мачка другите,се прави на интересен и да си мисли,че е Про ама НЕ Е!!! Винаги бих играл ДФ в момента няма смисал,защото нищо не бачка,но си трупам опита,за да мога да праскам на Хордите газа от Бой.С извинение към Екипа Ти се Обеси

**Comment by DarkAngel39** [comment]
Първо: Пачване на едно ядро от 5.0.5 на 5.4.2 или 5.4.7 е доста голяма работа дори и за големи групи от разработчици. Само да докараш ядрото до състояние, в което да можеш да логнеш с новия клиент, означава промяна на хиляди редове код. Да не говорим за оправяне на скриптове на магии и таланти, база данни и т.н. Който си мисли, че това е като да инсталираш flash player, не е за този сайт.
Второ: "Free server" официално е учебен проект, в който официално не се играе игра, а се тества сървър чрез wow клиента, понеже "по някаква случайност" сървъра използва същия протокол като wow клиента с определена версия. Всичко друго ще зарадва адвокатите на blizzard. Т.е. официално в нито един частен сървър няма играчи, а самия сървър е проект в разработка. Така че няма как да искате 100% blizzlike игра в който и да е частен сървър. На който това не му изнася, да плаща на bliz.
Трето: Както вече няколко пъти споменах в предишни теми, github е предназначен само за докладване на бъгове по играта. Ако намерите бъгната магия, куест или каквото и да е друго и това не е докладвано, го докладвате. Ако вече има написан тикет, няма смисъл. Всичко друго е за сайта на ДФ, а не за github.

**Comment by Mympa** [comment]
Attractivee.. твоето мнение мен не ме интересува... като знаеш много земи помогни с нещо за сървъра на който си мислиш че играеш. Аз си играя на Близард и мен не ме ебе за сървъра, но ме боли от такива като теб, които само на готово чакат и само критикуват! Ами добре седи си на сървъра и си играй на 5.1.0 а аз си играя на 5.4.7 и ми е готино. Бия си Гарош по 10 пъти  земам си итеми.. правя реални пари от играта, така че ти си седи тука и си гледай кефа!!
DarkAngel39... близард не ги ебе за тези пиратски сървъри по света. да си чул да е затворен някой европейски сървър? Аз не съм, няма и да чуеш!! Близард знаят че колкото и да се мъчат няма как да го направят даже и 50 % близлайк. ПОзнавам Приятел който бачка за Близард и е българин и затова коментирам! Обаче наистина тези ГМ-та са много ама много мудни и според мен не ги ебе за сървъра!! даже мисдля че не четат тука какво се пише. 
Айде лека от мен и се надявам да се оправите скоро!!

**Comment by DarkAngel39** [comment]
Mympa, като си биеш Гарош по 10 пъти и си вземаш предметите, от какъв зор спамиш тук? Знаем на кой пач е blizzard и че всичко си работи там. А отколкото до сървърите, blizz не спира частни сървъри, понеже няма правна пътека за това, а не защото не им дреме. Дори и да не са 100% оправени, частните сървъри представляват проблем за тях, понеже доста хора играят там безплатно. Голяма част от играчите, дори са хора, които са се преместили от оригиналните сървъри по една или друга причина. Това е загуба за blizz, имайки предвид и постоянно спадащия интерес към wow като цяло.

**Comment by Bleedeyes** [comment]
Уж нов собственик нови работи... ПЪК ТО СЪЩОТО
Хайде стига ядове ми лека и мека... може утре като логнем пък да има напредък... ROFL (trollface)

**Comment by Mympa** [comment]
DarkAngel39 спамя си тука щото имам 2 акаунта с герои и не мога да се реша да .. ги погледна, че незнам какво ще видя и намеря! Това добре! Близард земат 25 лв на месец, айде раздели го на 30 дни и сам и кажи колко е скъпо!! (друг е въпроса че ние не плащаме) аз лично не съм си плащал от 2 години ... Това "доста хора играят там" отнесено към европа според тен колко е като бройка хора? не повече от 250 хил. за цяла европа. (само европа). не забравяй че идва нов експанжън... и някои от така наречените стари играчи ще се върнат (поне за 2 месеца) за да видят за какво иде реч. Отлива на играчи от Близард започна от катаклизъм и след като пуснаха Пандария. Обаче след 5.4 пача доста хора си платиха само и само да набият канчето на Гарош (имам такъв в гилда). Близард ако кажат да спрат частните сървъри че ги спрат, не ги спират и контролират за да видят хората как е при частните, за да могат хората които играят на тях да се замислят и да си купят играта , която вече е доста евтина. Жал ми е за сървъра.. празен седи.. не е като едно време, когато аз играех (2006 или 2007 ) .

**Comment by DarkAngel39** [comment]
25 лева по 250 хиляди колко прави? :D По груба сметка е около 4,4 млн. долара (1,418 курс) загуба на месец за blizzard. А и в частните сървъри не влизат играчи само от Европа. Да, на 5.4 може доста хора да са си пуснали акаунтите за един месец, колкото да набият Гарош. А за следващия месец колко са си платили? Сега с новия експанжън безспорно ще имат прилив за няколко месеца, но играта вече стана банална. Ниво 100... представи си нов играч, който не знае нищо за wow, как ще се навие да им плаща за такава глупост. Това, че blizz официално не признават частните сървъри за проблем, далеч не означава че те не са такъв и че няма да спрат един частен сървър ако им се отдаде възможност. Засега това няма как да се случи с големите и доказали се частни, поради причините, които изредих по-горе. За да може да се случи това е необходима промяна в законите на съответните държави. На пример в С.А.Щ, хостинга на частни wow сървъри е нелегален. Но това не важи за Европа и не пречи на американците да логват в европейски частни сървъри. Иначе и аз помня когато ДФ имаше по 2к играчи на линия и даже съм чакал на опашка да вляза. Но времената се менят и интересите също. Щом на повечето хора 25 лв. на месец за една скапана игричка им се виждат малко, нека плащат на дебелаците от bliz и да си гледат там красивите пикселчета.

**Comment by Bleedeyes** [comment]
Четох че миналата година в периода юни-септември са направили 720 милиона само от акаунтите... грубо това са 2,5 милиарда  годишни приходи само от плащанията по акаунтите... имат полза и от пиратските сървъри, нещата са относителни :)

**Comment by Mympa** [comment]
пак идвам да напиша нещо, докато почивам от играта. С пускането на новия експанжън Близард предложиха буст на 1 герой по избор 90 лвл (ако си избрал професиите му .. те стават на макс скил), но това е само сега си купиш експанжиана, иначе по 60 долара за всеки друг герой ще се плаща(ако искаш да си дигнеш). Близард го направиха за да може някой нов за играта да скипне 1-90 лвл мъката да дигаш и да почнеш направо на новия контент. Хубави времена бяха на ДФ, жалко че сега няма как да се върнат поне 500 играчи! И казах че лично аз не съм плащал на Близард от поне 1година и половина! продавам голд-а  който искарам за 2 месечна карта(може и повече) ..........Да видим сега на 5.04 какво ще постнат в ФБ :) за оправените неща в играта :)

**Comment by DarkAngel39** [comment]
Да, запознат съм с безплатния първи герой 90. Представи си съвсем нов играч, който няма ни най-малка представа какво се прави, как ще играе с този 90 lvl. Ще има лесно фармене на honour с новия им експанжъм xD. Каквото и да си говорим, интереса спада. Ще трябва все по-често да създават нови и нови неща, за да задържат играчи. А това безспорно ще рефлектира върху новите, на които играта ще им изглежда все по-тъпа, понеже ще става все по-трудно да разберат какво се прави в нея.

**Comment by Min4AKK** [comment]
Za men pandata e dosta po lesna ot licha

**Comment by Min4AKK** [comment]
Za nqkoi neshta pone si pishe kakvo se pravi,za drugi se iska chetene,no vseki si ima sobstveno mnenie

**Comment by DarkAngel39** [comment]
Едно е да прочетеш магиите си, съвсем друго е да можеш да играеш играта и да се научиш кога да ги използваш, било то в pvp или pve. А отколкото до по-лесното: Да, пандата ти е по-лесна от лича, защото си играл от лича или от по-рано. Т.е. не си нов играч, влизащ за първи път с ниво 90 герой. :D

**Comment by Bleedeyes** [comment]
Яд ме е че промениха талант бийлда...а и сега е много улеснено и буквално за всеки куест или постижение всичко пише, показва ти къде да отидеш, какво да убиеш, като за 6-10 годишни деца...

**Comment by Min4AKK** [comment]
E ti kvo iskash da ne znaesh kvo da pravish I da se chudish zashto igraesh :D

**Comment by DarkAngel39** [comment]
Като започнеш една игра не знаеш какво правиш. Имаш представа какво трябва да е, но едно е да знаеш на теория нещата, а практиката е съвсем друго. За това хората са измислили нивата. Почваш от 1 ниво, където нещата са прости и постепенно получаваш нови и нови неща със всяко ниво. Ти да не си се родил научен да играеш wow? :D

**Comment by Bleedeyes** [comment]
Това ми е ясно... но не може да отречете че вдетиниха играта... дори графиката и съществата са като от някоя хипи анимация :D

**Comment by Mympa** [comment]
нека да поясня ; когато си боостнеш герой на 90 лвл , играта не те пуска директно да играеш с него а минаваш, нешо като ДК-тата предкуестове да се научиш да си ползвеаш скиловете поне, дават ти и геар 483 ИЛ зелен, с който за жалост скипват 2 райда и хероик инстанциите, и скачат на последните два райда ТоТ и СоО . То отсега има такива герои, аз поне го облякох с епични итеми и сум го енчантнал и ферордженал и си прави приличен дпс на райдовете и БГ-дите !! Улеснена е доста играта, спомням си времето когато трябваше на 2 левела да ходиш да учиш магии, сега нема такова нещо, всичко е в движение, само се връщаш за райдинга да го научиш :) таланти на 15 левела(вярно направили са ги добре) дамадже има бол, хелинг още повече, ама и босовете като цяло си дават яко.. Наскоро дигнаха Хп-то на босовете в алтерак че нещо много бързо падаха :) Истината е че повечето играчи имат по 30 героя на акаунт и не ги ебе дали знят или незнаят да играят, фермери им викат. :) киснат по дял ден в АХ-са и дебнат. Нещо ново по сървъра ? не смея да вляза даже .. ще ме хване яд и може да затрия героите ;)

**Comment by Min4AKK** [comment]
Ami veche e otvoren 5.0.5 :)
