### ISSUE TITLE
Има ли смисъл да се връщам или да си стоя в Heroes-WOW

### ISSUE THREAD

**Issue by Ivailo3007** [DragonFire/panda#253]
От близо месец не съм влизал. Някакви подобрения има ли ?

**Comment by Bleedeyes** [comment]
Днес в 18;30h имаше 6 алита онлайн в wotlk и 20 в pandaria реалма... в момента 20:10h има 10 онлайн в wotlk и 22 в pandaria реалма. Толкова зле не съм го виждал сървърът, а играя от 2008. :( RIP

**Comment by Min4AKK** [comment]
Podobrenie ne no zazlevqvane sus sigurnost

**Comment by Ivailo3007** [comment]
oki ms za infoto.
OSTAVAM SI V HEROES WOW
POVE4E NQMA DA 4UETE OT MEN

**Comment by FALL1N1** [comment]
Скоро ще има тонове обновления по WoTLK така и в Pandaria. :)
