### ISSUE TITLE
Doomshroom бъгнат герой след смяната на пача.

### ISSUE THREAD

**Issue by doomshroom** [DragonFire/panda#254]
Немога да вляза с героя. Играта крашва точно преди да зареди. Мога да вляза с други герои от същият акаунт.

**Comment by stennka** [comment]
моя герой също неможе ( Deathmantle )

**Comment by yukiri** [comment]
Здравейте,

След пача на мен ми дава, че имам свободни таланти, но като натисна Learn, пак стоят свободни. Героя ми е Itkovian.

**Comment by ongamex** [comment]
На кой пач сме вече?

**Comment by Min4AKK** [comment]
5.0.5 I povecheto 90ki ne mogat da logvat,nz zashto :D inache vsichki achievementi osven guild achievementite sa izchisteni,no te ne sa problem

**Comment by Min4AKK** [comment]
Koito e ot Malediction ima Realm First za guild na servera ;) :D I da v nai-skoro vreme shte zapochnat da opravqt bugnatite geroi

**Comment by Min4AKK** [comment]
Vynstus

**Comment by doomshroom** [comment]
Doomshroom

**Comment by DarkAngel39** [comment]
Ninja

**Comment by Peturmetala** [comment]
Peturdk

**Comment by spraypaint1993** [comment]
spraypaint

**Comment by tribaler0** [comment]
Eliotkid - bugged, Autaila - deleted Achievements

**Comment by doomshroom** [comment]
Desirea

**Comment by tribaler0** [comment]
Belissima, Delgado, Ortus

**Comment by stennka** [comment]
Deathmantle

**Comment by tzarbbc** [comment]
Hauler, Rusadrysla

**Comment by tzarbbc** [comment]
Charlize, Amillia

**Comment by vasilii11** [comment]
Jast,Maxi

**Comment by marto0oo** [comment]
Frostmagee

**Comment by doomshroom** [comment]
Bloodname

**Comment by tzarbbc** [comment]
Hauler, Rusadrysla - premesteni sa v OG no pak errorva...
