### ISSUE TITLE
Battle net account bug.

### ISSUE THREAD

**Issue by rjgnehgoej** [DragonFire/panda#255]
Ot dva dni ne moga da se logna v akaunta si (v panderia realma) kakvoto i da pravq. Postoqno mi izpisva suob6tenieto: Please log in with your battle net account name and password. Kakvo da pravq ? Ot men ili ot survara e problemut ?

**Comment by FALL1N1** [comment]
5.0.5b ли си и сложи ли правилния realmlist?

**Comment by rjgnehgoej** [comment]
Az sum na  5.1.0 i sum sus realmlista ot saita : SET realmList "pandaria.guildszone.com". V poslednite 5 dni nqmah problemi sus tazi versiq i realm.

**Comment by FALL1N1** [comment]
Сървъра вече е на 5.0.5b.. Moжеш да свалиш клиента от тук: http://filebeam.com/a48a123b0130ad4a4960e12f037b9604

**Comment by rjgnehgoej** [comment]
Blagodarq, hmm sigurno sum  propusnal da go vidq, nov sum i nz kude da gledam za takiva raboti.
