### ISSUE TITLE
Dragonspower banove?

### ISSUE THREAD

**Issue by imbaskill** [DragonFire/panda#256]
Zdraveite,ot TBC igraq v DF i nikoga dosega ne sum bil warn-van ili banvan za kakvato i da e bila ne4estna igra.Slu4i se oba4e o6te na predi6niqt pa4 4e ot nqmane na kakvo da se pravi v servera sled kato digne6 90-ti level 1 priqtel nameri bug za pravene na gold s izpolzvane na macro za po-lesno i se vuspolzvahme ot nego oba4e vednaga bqhme hvanati v kra4ka o6te predi da mojem da pohar4im i stotinka ot nego ot Dragonspower koito vednaga go iztri(golda) i ni banna pernamentno.Vuprosa mi e sledniq:tui kato golda ve4e e iztrit ne moje li bana da ne e zavinagi,a kakto pi6e vuv foruma vuv temata poso4ena ot GM Seducer-razdel pravila,a imenno 4e za polzvane na bugove bana obiknoveno e ot 5 do 15 dni,a 4ak za polzvane na hackove ili ako si banvan nqkolko puti za bugvane e permaban?Nerazbiram glednata to4ka,to ako se sledvat pravilata vsi4ki trqbva da sa bannati,za6toto vsi4ki classove i talanti sa bugnati po 1 ili drug na4in i izpolzvaneto na tezi magii su6to se vodi polzvane na bug.Nakratko 6te moje li gm-a koito e slojil banovete da napi6e 1 red dali smqta v bude6te da gi mahne(no ne kogato ostanat samo GM-mi v servera bez nikakvi igra4i) ili napravo az i moq priqtel da si tursim drugi serveri.

acc-tata sa holytupanik i l3d0razb1va4,no su6to taka acc-ta morgull i cha0s_r1d3r bqha bannati bez nikakvi osnovanie,bez da sa polu4ili absoliutno ni6to ot bugva6tite acc-ta,bih kazal na absoliutno izbiratelen i samovolen princip

**Comment by imbaskill** [comment]
nikva programa ne sum polzval,razlika mejdu macro i programi pravi6 li?

**Comment by marto0oo** [comment]
pi4 Dragonspower e mnogo pekan Gm,taka 4e 6tom ti go e slojil ima za6to!!! ospami i foruma i fb i tuka stiga!!! tozi sait e za reporti,a ne za bannove ili koi kvo napravil!!!

**Comment by imbaskill** [comment]
pi4ove ne 4e ne6to ama mnenieto vi ne me vulnuva osobeno,temata e za konkreten 4ovek prosto za6toto predi da slojat pa4a ticket sistemata e bugava i gm-a be6e truden za otkrivane za tova pi6a tuka,sega ve4e govorih s nego.lock.
