### ISSUE TITLE
Galleon (world boss)

### ISSUE THREAD

**Issue by spraypaint1993** [DragonFire/panda#268]
World Bossa Galleon (http://wowhead.com/npc=62346) lipsva.Dobre shte bude da go addnite,poneje v momenta edinstveniq nachin chovek da se gearne pve e ot repove,profesii ili da bie sha of anger (koito dropva po 1 item )

**Comment by onsgame** [comment]
за този босс поне 40+ играчи трябва за да го убиете още в сървара няма толкова играчи за да го убият :)

**Comment by spraypaint1993** [comment]
vtori den podred biem sha of anger i dnes bqhme nad 30 choveka,taka che kato ne znaesh za kakvo stava vapros ne komentirai :)

**Comment by FALL1N1** [comment]
Добре, ще хвана да го направя :)

**Comment by FALL1N1** [comment]
Boss-а е пуснат, моля пиши ако има проблеми с него.

**Comment by onsgame** [comment]
to hubavo che go biete nqma losho :)

**Comment by Mympa** [comment]
да не забравяте да си земате койнс за бонус лут от Боссовете :)

**Comment by spraypaint1993** [comment]
Bossa e pusnat dobre,obache dnes kato go ybihme nqmashe loot,tova e ediniq problem,drygiq e che respawn time my e malak.(okolo 10 min ),dobre shte bude da go napravite 1 den kakto e na sha of anger,s yvelichavaneto na populaciqta v sarvara dobra ideq shte bude da se namalqt respawn time na bosovete poneje ako sled vreme stane taka che da ima po 500+ players online,to horata shte se izbivat za teq bosove

**Comment by Mympa** [comment]
respowna na tezi dwa bosa e ; Sha 2 chasa  Galeon 2 chasa, taka che ne e 24 chasa

**Comment by Attractivee** [comment]
Mympa къде го прочете това?

**Comment by FALL1N1** [comment]
Оправен е и loot-а. Ако има нещо пишете :)
