### ISSUE TITLE
Sell CD

### ISSUE THREAD

**Issue by tribaler0** [DragonFire/panda#283]
Ако е възможно да се оправи проблема с продажбите. При пълен инвентар отнема доста време да продадеш нещата на NPC, когато трябва да чакаш по 3-4 сек. след продажбата на всеки предмет, за да продадеш друг.

**Comment by FALL1N1** [comment]
V petuk shte e opraven

**Comment by Thars** [comment]
В кой петък, 2015г. ли... защото още не е оправено.

**Comment by FALL1N1** [comment]
Днес ще бъде оправено, съжелявам.

**Comment by Dude100** [comment]
/_post1 :D_/
-    uint32 now = getMSTime();
-    if (now - timeLastSellItemOpcode < 100)
-        {
-            _player->SendSellError(SELL_ERR_UNK, creature, itemguid);
-            return;

**Comment by Dude100** [comment]
/_post 2 :D_/
-    if (counter != _player->m_timeSyncCounter - 1)
-    if (clientTicks != _player->m_timeSyncCounter - 1)

**Comment by Dude100** [comment]
/_post3 :D_/
-        time_t timeLastSellItemOpcode;
-        uint32 timeLastSellItemOpcode;

**Comment by Dude100** [comment]
i Emilqncho vlachi za DF :P

**Comment by Dude100** [comment]
i gledai do ytre da e gotovo xorata da se kefqt :1234:

**Comment by FALL1N1** [comment]
Защитата от DoS е премахната от много време, проблема е от самия Opcode и структурата му.
