### ISSUE TITLE
Leyara Missing!

### ISSUE THREAD

**Issue by Pichaga1997** [DragonFire/panda#289]
Nqma go Npcto Leyara: ( http://www.wowhead.com/npc=53014 )
http://s13.postimg.org/ckbmvyx07/Wo_WScrn_Shot_041314_101622.jpg

**Comment by AnTOLI** [comment]
Няма го да адд това Нпц сигорно . :)

**Comment by FALL1N1** [comment]
Сега ще го добавя.

**Comment by FALL1N1** [comment]
Добавено е но не е кодирано.

**Comment by AnTOLI** [comment]
Не може да се атакува Нпц то ако може да го оправите.

**Comment by FALL1N1** [comment]
След рестарт ще е оправено.
