### ISSUE TITLE
Стой на Auntenticating

### ISSUE THREAD

**Issue by theXz** [DragonFire/panda#297]
Здравейте !
Искам да се логна с акоунта си в сервера. В сайта на ДФ нямам проблем. Изтеглих си 5.0.5 , но стига до Auntenticating и просто стой така . Моля за помощ.

**Comment by Attractivee** [comment]
Новият реалм?
 SET realmList "77.78.132.3"

**Comment by FALL1N1** [comment]
Ако има проблеми отвори отново.
