### ISSUE TITLE
Проблем с Гилдиите!

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#299]
При Гилдия Devastation както и при други има проблем с ачиевементите и от там с Guild Vendor-a, нямаме ачиевемент за вдигнато 25 нови, само за 5.Моля ачиевементите да бъдат оправени някак..

**Comment by Aerohax** [comment]
Същия проблем го има и при гилдията Chaos and Destruction

**Comment by Pichaga1997** [comment]
xaxa ako ne mi bqhte videli skorpiona,vuobshte nqmashe i da gi vidite tiq achievmenti che lipsvat :D

**Comment by Bleedeyes** [comment]
Osven tova ima problem s GUILD CONTROL... promenite ne se zapazvat ili go pravqt neznaino kak (kogato relogna nqkoi tick4eta se mahat, drugi sa tam... !???wtf?) Sy6to taka daily-tata ne davat guild xp, samo guild repotation.

**Comment by FALL1N1** [comment]
Не се записват защото няма opcode а и няма от къде да го вземем.

**Comment by Attractivee** [comment]
Записват се, но трябва да се направи по специфичен начин...след направата на ЕДНА промяна, затваряте прозореца и така навсякъде, за да се сеифат.

**Comment by spraypaint1993** [comment]
Guildiite Nefelin i Malediction sashto imat tozi problem s achievementite, i dvete guildii sa 25 level ,no v achievement panela pokazva samo 5 level achievement,molq da gi opravite v nai skoro vreme

**Comment by Attractivee** [comment]
Всичко е оправено при нас (Devastation), благодаря.
Освен гилд менюто, разбира се...
