### ISSUE TITLE
Soul Bound Problems and missing recipes

### ISSUE THREAD

**Issue by tribaler0** [DragonFire/panda#306]
Липсват рецептите за "Black Smithing" от репутация "Klaxxi" - http://wowhead.com/npc=64599#sells

**Comment by spraypaint1993** [comment]
"scrol of wisdom" и " imperial silk",ТРЯБВА да cа  sb,parvo proveri wowhead i togava pi6i......
a otnosno Bs receptite mislq 4e ako nqma6 nyjniq rep moje6 da gi vidi6 daje da gi kupi6 no stigne6 li revered izchezvat.
