### ISSUE TITLE
<Klaxxi Quartermaster>

### ISSUE THREAD

**Issue by Powerr** [DragonFire/panda#310]
Проблема с 13-те рецепти за Блексмитинг от Куортър-мастъра в Клакси беше репортнат няколко пъти вече , явно не се обръща голямо внимание на написаното тук , но това е единственото място , където можеш да пишеш и някой от Девовете да го пречете с безмислени тикети в играта е ясно , че няма смисъл . Репортвам това , което чакат 20% от играещите хора (и ще го репортвам всеки ден докато не се вземат мерки не е нещо толкова непосилно адването на 13 рецепти в 1 вендор).  " http://wowhead.com/npc=64599#sells липсват.
Трябва да се продават на хоноред репутация с/у 20 броя kyparite - http://wowhead.com/item=72093

**Comment by FALL1N1** [comment]
fixed
