### ISSUE TITLE
Paladin Spell " [Word of Glory]"

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#33]
Ефекта на тази магия е следния:
В зависимост от това, колко Holy Power имаш, магията heal-ва, колкото повече Holy Power, толкова повече heal.

Проблема е, че само абсорбира Holy Power, без да хелва.
http://www.wowhead.com/spell=85673/word-of-glory

**Comment by 3DViking** [comment]
Готово, оправил съм го в тестовия сървър, до няколко дни ще го кача на сървъра.
