### ISSUE TITLE
ADMINS !!!

### ISSUE THREAD

**Issue by tribaler0** [DragonFire/panda#345]
Драги ми админи или подлизурковци, приемете убидите като комплименти, защото продалжавате да прецаквате работещи неща: 
http://www.wowhead.com/spell=8033/frostbrand-weapon
На някой му скимнало, че е бъгаво и шотвало и хоп спряхте го. Същото стана и с Warlock (whole class и най-вече "http://www.wowhead.com/spell=108503") защото много бие и талантите му работят, затова решихте да спрете всички работещи спелове и да играем с 1 умение. По тази логика спряхте и на ДК-то "http://www.wowhead.com/spell=81256" защото биел по 20к. 
Хайде вземете се стегнете и разкарайте тъпите пишлемета (16-18 годишни) от админите и повишете някой, който разбира от играта и знае за какво става въпрос - било то някой от старите "bugtrackers" или някой от играчите в тест сървъра. Стига с тези малки пишлегарчета, които ревът, че уменията на геройте са бъгави, затова падали на дуел и вие им вярвате и спирате работещи неща без да ги тествате! Спрете да си измисляте причини поради, които не отговаряте на тикети и въпроси.

БЪДЕТЕ МЪЖЕ И ЛОГНЕТЕ ИНГЕЙМ ЗА ДА ДАДЕТЕ МАЛКО ИНФОРМАЦИЯ НА ИГРАЧИТЕ!!!

**Comment by delux987** [comment]
+1

**Comment by Lycana** [comment]
Абсолютно вярно , но така е почти за всеки клас много спелове не работят, самата продажба на итеми не работи, няма инсове дънджове  пълна мизерия , професии, 
Моля ви скъпи приятели оправете малко сървара ;)

**Comment by spraypaint1993** [comment]
podkrepqm mnenieto che ima nyjda ot GM-ta koito igraqt v sarvara i znaqt kakvi problemi ima i koe e nai vajno da se opravi,plus tova ima nujda  i ot komunikaciq mejdy igrachite i game mastarite,ne moje 1 change log koito stoi ot 1 mesec da pokazva che ima 3 dungeona i 1 raid otvoreni a defakto nqma ni6to.random battlegroundite davat po 15 honor na pobeda (tova e o6te otkakto minahme na 5.0.5) pri tolkova honor na pobeda e izkluchitelno trudno da se vzemi 1 item a kamoli novite igrachi da se gearvat,galleon go reportnah che go nqma - ok addnahte go ,no e addnat bez nikakav loot i bez nikakav immunitet (moje da se stunnva,rootva,fearva i tn.) drygoto koeto sam zabelqzal che samo edin gm otgovarq na ticketite (seducer) koito e 1 level i nqma koi znae kakva informaciq i vazmojnostta da pomaga s naleja6tite problemi.

Molq ne razbiraite tozi komentar kato "agresiven" ,a kato gradivna kritika,nadqvam se che ne sam zasegnal nikoi.

**Comment by tribaler0** [comment]
По логиката на Attractivee, направо да спрът сървъра, като не могат да оправят нещтата. След като повече от 2 месеца чакаме фикс а те не могат да го предотставят направо няма смисъл да се занимават. 

Stennka ли си какъвм си, като не познаваш хората в един отбор просто не се опитвай да пишеш глупусти. Вземи порасни и разбери, че има и други неща освен тъпия ти хейт към по-добрите играчи!

**Comment by FALL1N1** [comment]
@stennka Айде като си такъв дев ела и го оправи и имаш 100лв от мен :)
