### ISSUE TITLE
CRASH BUG!!!

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#39]
Мисля, че намерих краш бъг.Но няма да го споделя тук.Ако е възможно някои ГМ да ми пише ингаме, за да тестваме дали наистина е краш бъг.
3 пъти крашна сървъра след извършване на съответното деиствие, на това основание пиша тук.
Attractivee ми е героя.

**Comment by pendulum91** [comment]
то крашна 10 пъти вече...

**Comment by 3DViking** [comment]
какъв ти е героя

**Comment by pendulum91** [comment]
моя е warrior, на атрактив мисля че, е паладин ?
в момента се скъсва да крашва.

**Comment by Attractivee** [comment]
Оказа се, че не е краш бъг.
