### ISSUE TITLE
Judgment причинява краш

### ISSUE THREAD

**Issue by ongamex** [DragonFire/panda#392]
4 пъти подред ми се случи, съмнява ме да е съвпадение!

**Comment by Larua** [comment]
Spell: Class C - VIB

**Comment by FALL1N1** [comment]
Ще го проверя.

Update: При мен го няма този проблем.. кой Seal използваш?

**Comment by ongamex** [comment]
беше insight, Imoogi е героя

**Comment by ongamex** [comment]
смених seal-a и продължава

**Comment by FALL1N1** [comment]
Windsong li e enchanta na orujieto ti?

**Comment by ongamex** [comment]
Да windsong e,
бъфове Fae Song, Blessing of Kings, Pursuit of Justice

**Comment by FALL1N1** [comment]
Ясно.

**Comment by ongamex** [comment]
Пак крашна, иамам трансмог ако е от него

**Comment by ongamex** [comment]
сега ще пробвам с друг weapon (бтв. съветвам да напишете едно съобщение в world chat-a)

**Comment by ongamex** [comment]
Току що пробвах с друг паладин Imoogenheap не се получи

**Comment by ongamex** [comment]
Да вече и с Imoogi не се получава

**Comment by FALL1N1** [comment]
Спрях енчанта временно (до няколко дни) ще го оправя възможно най-скоро.

**Comment by FALL1N1** [comment]
Не бъди толкова сигурен, след няколко дни го пускам ;)
