### ISSUE TITLE
MoguShan 1вите босове

### ISSUE THREAD

**Issue by ongamex** [DragonFire/panda#395]
Имат проблеми основно Jasper Guardian ни прави на камън и неможем да мърдаме целия райд. След алт + ф4 НЕ се оправя!

**Comment by FALL1N1** [comment]
Ще го погледна.

**Comment by FALL1N1** [comment]
Ще бъде оправено до 3дни (рекомпилация на реалма)

**Comment by FALL1N1** [comment]
Оправено!
