### ISSUE TITLE
Закриването на DragonFire-BG.net

### ISSUE THREAD

**Issue by Pichaga1997** [DragonFire/panda#408]
Не си правете труда и грижите.Не си хабете нервите и надеждите напразно.Не стана ли ясно че вече няма бъдеще в сървъра.За 3 месеца се мъчиха само с един райд,който просъществува около седмица само и то колко просъществува още на 1 бос проблеми,а и от тия 3 месеца колко време са посещавали ДФ.Едни се мъчат да правят неща които не са им по силите а други си цъкат си в Близз и въобще не ги интересува какво се случва тук и какво не само някой път ей тъй от скука да влязат да видят нещо.Те вече са се отказали от сървъра и се надяват на милосърдието на остатъка от заблудените и вманиачени в героите си фенове.Не само че не правят нищо ами и допускат единствените що годе работещи неща да се развалят-спеловете.Днеска влязох за 10 мин и видях че на паладина не му работи Execution Sentence,а и други работи сигурно,за които не знам,но и не желая.Мен лично както повечето хора ме загубиха като играч.Сървъра беше най-играният Бг сървър с повече от 2500 човека и с почти всичко работещо преди  5,4,3,2 години когато беше на лича,което си е много добре даже.Не съм чувал в сървър да се задържат толкова хора за толкова време което е похвално,но всяко едно нещо с времето си остарява и поомръзва  и една голяма част се оттегли през по-миналата година в прогресиращия молтен който беше пръв сървър на 4.3.4 доколкото помня а след това и от други сървъри се появиха там.Нормално е на човек да му омръзне едно нещо което прави постоянно от 4 години и е хубава идеята за преминаване на по-горен пач,но щом това се е оказала толкова трудна задача за осъществяване ( особено от лич към панда)защо просто не кажете че не можете или че не ви достигат средства или хора там какъвто е проблема,вместо да се дават напразни обещания които не можете да изпълните и само да се разочароват хората.Ами така си е в крайна сметка.Сървърът е отворен от началото на Януари сега сме юни и какво се е оправило оттогава-няма работещи инсове,няма работещи райдове (от месец някъде не работи и хероика на ТБК и Лич инсовете),няма работещи арени,не се дават точки от Бгта,не работят много спелове,професиите също са много зле и то друго не остана какво да се прави освен дейлите,а дори и Лвл куестове за реп трудно стават тъй като са много бъгнатите.Няма смисъл от напразни обещания и напразни коментари след като не може да се поддържа сървъра.Колко от написаното в Changeloga е вярно а и по коментарите тук също.След като сте решили да запазите сървъра го направете като хората но след като нищо не може да се направи по въпроса го затворете по-добре сървъра.То и без това натам е тръгнал.И дори сега да се случи някакво чудо и да успеете да закърпите сървъра което повечето хора видяха как става за известно време и примерно дойдат малко повече хора да видят за какво става дума все ще се бъгне нещо и като не можете да го оправите какво става после пак старата история.Той добре си поживя сървъра,добре се развиваше,доста дълго дори смея да кажа,но както знаем всяко нещо си има край колкото и да не ни се иска.Затова предлагам щом не може никой да поправи нищо в сървъра или няма желание,то по-добре е да се затвори.Щом за 6 месеца нищо не се е подобрило освен бъгнатия демидж на warriors как тогава всичко отизведнъж да проработи.Пробвали сте се добре е това,никога не може да бъде сигурен човек преди да опита,но и не винаги става.Безмислено е да се уморяват играчите в ядосване на бъговете и в чакане на невъзможното и персонала който е безсилен да оправи сървъра и многобройните бъгове.Той е вече духовно затворенв този си му вид,та безмислено да се отлага повече.Поне ще остане дълго време в сърцата на всички които са играли тук и ще го помнят дълго време та кой знае може да разказват на синове,внуци,правнуци...Това си е само мое мнение разбира се,не мога да задължа никого да прави каквото и да е било,но само казвам как стоят нещата и с най-добронамерена цел отправям това предложение,макар и леко грубовато в началото.

**Comment by Pichaga1997** [comment]
Дори не държа да ми отговаряте освен ако нещо аз греша или нещата стоят по друг начин особено съм против безсмислени обиди и спорове от страната на най-запалените само защото не искат да се разделят с героите си,които сигурно са им най-близките "Хора"които са до тях във всеки един момент тъй като не стават от компютрите си,но то си е за тяхна сметка.Всеки решава как да си живее живота си.Не принуждавам никого да прави каквото и да е било и не настоявам за нищо,а просто искам да се замислят останалите които все още крепят някаква надежда.Аз самият няколко пъти съм се отказвал и съм си давал героя и съм си го трил но пак съм се връщал въпреки всичко,но с времето си дадох равносметка че няма повече смисъл от това играене.Все някога ще бъде затворен сървъра независимо дали сега след 3,4,5...години.Добре интересно е било и сървърът е бил добре но какво от това.Той е само временно явление.Няма да бъдат вашите герой тези които ще ви подкрепят за първа среща с любим човек,за трудности в училищетo,спорта,взаимоотношенията с хората ви,няма да присъстват на вашата сватба,на раждането на вашето дете,на празници като Коледа,Великден а и други,няма да са до вас на рождените ви и именни дни (Това е за по-младите).Пък замислете се.Дори и да не затворят сървъра сега,какво може да се случи за да се задържи като такъв,колко още му остава.

**Comment by Pichaga1997** [comment]
Ако няма какво да кажете или не сте съгласни с мен,най-малко проявете уважение за времето,което съм отделил за всички вас :)

**Comment by Attractivee** [comment]
Прочетох само заглавието, но ще ти кажа следното:
Не ти харесва ДФ?Не играи в ДФ, никой не те е задължил.
ДФ е частен сървър, тоест нищо в играта не е твое.
Издова какъв е, ти си никой в този сървър ако ще и 10 години да си играл :)

**Comment by Attractivee** [comment]
Друг е въпроса, че има хора като мен и теб, като мен който се опитват да подкрепят българското  с нещо и хора като теб, на който не им се чака и не им изнася все нещо, които " добронамерено"  плюят сървъра.НО нито ти, нито някой друг ще кажете кога, ще се закрие ДФ, защото има СОБСТВЕНИЦИ, който решават какво да става със сървъра!
По-просто казано, ако искаш на челна стойка се побии, НЯМА НИКАКВО ЗНАЧЕНИЕ :)
И аз като теб добронамерено ти го казвам, защото си е така както и да го погледнеш.

**Comment by FALL1N1** [comment]
Здравей! Сега ще ти обясна защо няма ъпдейти, нови райдове и т.н
Ще започна от там че съм един обикновен ученик учещ в техническа гимназия с специалност електроника а не програмиране или нещо свързано с компютри.
Аз съм "може да се каже единственият девелопър защото съм най активен" единственият който се занимава с оправянето на бъгове и мога да работя само събота и неделя защото нямам финансовата възможност да си позволя лаптоп от който мога да компилирам с C++ без да се съсипе за два три месеца. 
А и друго че уменията ми не са на професионален девелопър а просто 18 годишно хлапе с хоби към сървърите. 
Този месец след като приключа училището ще отделя една седмица да ви изслушам всички и да оправя колкото се може повече бъгове.

**Comment by FALL1N1** [comment]
Извинявам се за граматичните и правописни грешки защото пиша от телефона и поправя автоматично.

**Comment by Dude100** [comment]
@JunkyBulgaria пак ме развесели :+1:

**Comment by Jxlock22** [comment]
@JunkyBulgaria, малко късно но, има ли някакъв шанс да се съживи сървъра? Преди доста години аз също играх там с приятели и това беше един от най-свестните български сървъри. Ако решиш да го пуснеш бих помогна с каквото мога. Имам някакви познания по системна администрация и базови знания по програмиране.
