### ISSUE TITLE
Missing NPC Li Li ID 56138

### ISSUE THREAD

**Issue by AnTOLI** [DragonFire/panda#428]
Нпц липсва в играта на дедото място  http://www.wowhead.com/npc=56138

**Comment by FALL1N1** [comment]
На мястото си е.

**Comment by AnTOLI** [comment]
Нпц го има но те атакува като си до него не е приятелски настроен. И живота му е 1 HP.

**Comment by FALL1N1** [comment]
Пусни нов репорт за тези неща защото този го затварям.
