### ISSUE TITLE
Class: Full Class Report

### ISSUE THREAD

**Issue by tribaler0** [DragonFire/panda#440]

**Comment by smotanqci** [comment]
g/d biva , ama imash dosta propuski, na hunta peta na BM pravi nad 60k Kill Command! pod 50k nikoga ne udrq, ai da vidim koi class shte izdyrji na 60k + dmg na vseki 6 sec i to samo ot Kill Command , da ne govorim , che bite pravi i toi 50k ??? To e qsno na toq patch nqma da ima raznoobrazie na clasove, vsichki hunteri na BM , vsichki DK-ta na Blood , warrove arms i drudite na mechka , tova shte e

**Comment by Charmey** [comment]
Има някои пропуски и несъответсия при друида, а именно:

Berserk (Bear Form) - не удря 3 таргета, а само 1;
http://www.wowhead.com/spell=106952

Bear Hug - прави 10% dmg от живота на друида, не от този на bear form;
http://www.wowhead.com/spell=102795

Faerie fire - ресетва куулдауна на mangle всеки път;
http://www.wowhead.com/spell=770

Аquatic Form - няма проблем със скоростта;

Revive - взема константно число от маната, изпробвано на Guardian и Restoration;

Bear Form - дава правилните бонуси, но с няколко (5-10)% разлика;

Hurricane - винаги превърн ато в Astral storm (http://www.wowhead.com/spell=106996) без да има активиран Lunar Eclipse (http://www.wowhead.com/spell=79577);
http://www.wowhead.com/spell=16914

Що се отнася до Typhoon, при мен автоматично се взема Mass Entanglement (http://www.wowhead.com/spell=102359), което не позволява да се научи който и да е от другите 2 таланта. Възможно е и при други да го има този проблем.
Иначе всичко друго описано по Guardian и Resto Druid е правилно.

**Comment by Enragelolz** [comment]
```
                                     Talents and Glyphs
```

---

```
                                         |Warrior|
```

1) Talents
"Double Time"
http://www.wowhead.com/spell=103827

"Safeguard"
http://www.wowhead.com/spell=114029
-Ne redirectva sledvashtata ataka

2) Glyphs

a)Major
"Glyph of Enraged Speed"
http://www.wowhead.com/item=43413
- dava bonusa postoqnno

"Glyph of Gag Order"
http://www.wowhead.com/item=43418

"Glyph of Overpower"
http://www.wowwiki.com/Glyph_of_Overpower

"Glyph of Sweeping Strikes"
http://www.wowhead.com/item=43428

"Glyph of Victory Rush"
http://www.wowwiki.com/Glyph_of_Victory_Rush

"Glyph of Hold the Line"
http://www.wowhead.com/item=43424
- procva na vseki udar

"Glyph ofShield Slam"
http://www.wowhead.com/item=43425

b)Minor
"Blazing Trail"
http://www.wowhead.com/item=85221

"Might Victory"
http://www.wowhead.com/item=43400

"Mystic Shout"
http://www.wowhead.com/item=43395

"Bloodcurdling Shout"
http://www.wowhead.com/item=43396

---

```
                                         |Death Knight|
```

1) Talents
Vsichko e tok i jica.

2) Glyphs

a)Major
"Glyph of Death and Decay"
http://www.wowhead.com/item=43542

"Glyph of Death Coil"
http://www.wowhead.com/item=45804

"Glyph of Shifting Presences"
http://www.wowhead.com/item=43543

b)Minor
"Glyph of Death's Embrace"
http://www.wowhead.com/item=43539

"Glyph of Horn of Winter"
http://www.wowhead.com/item=43544

"Glyph of Path of Frost"
http://www.wowhead.com/item=43671

"Glyph of Resilient Grip"
http://www.wowhead.com/item=43672

"Glyph of Tranquil Grip"
http://www.wowhead.com/item=45806

---

```
                                         |Mage|
```

1) Talents

"Blazing Speed"
http://www.wowhead.com/spell=108843
- procva pri cast

"Incanter's Ward"
http://www.wowhead.com/spell=1463

2) Glyphs

a)Major
"Glyph of Water Elemental"
http://www.wowhead.com/item=45736

"Glyph of Spellsteal"
http://www.wowhead.com/item=42754

"Glyph of Fire Blast"
http://www.wowwiki.com/Glyph_of_Fire_Blast

b)Minor
"Glyph of Conjure Familiar"
http://www.wowhead.com/item=43359

"Glyph of Crittermorph"
http://www.wowhead.com/item=42751

"Glyph of Illusion"
http://www.wowhead.com/item=45738

"Glyph of Loose Mana"
http://www.wowhead.com/item=42735

"Glyph of Mirror Image"
http://www.wowhead.com/item=45739

"Glyph of Monkey"
http://www.wowhead.com/item=43360

"Glyph of Porcupine"
http://www.wowhead.com/item=43339

"Glyph of Rapid Teleportation"
http://www.wowhead.com/item=63416

---

```
                                         |Warlock|
```

1) Talents
"Grimoire of Sacrifice"
http://www.wowhead.com/spell=108503

"Grimoire of Supremacy"
http://www.wowhead.com/spell=108499

2) Glyphs

a)Major
"Glyph of Dark Soul"
http://beta.wowhead.com/item=110864

"Glyph of Demon Training"
http://www.wowhead.com/item=42460

"Glyph of Life Tap"
http://www.wowhead.com/item=45785

"Glyph of Shadowflame"
http://beta.wowhead.com/item=110868

"Glyph of Demon Hunting"
http://www.wowhead.com/item=45780

"Glyph of Conflagrate"
http://www.wowhead.com/item=42454

"Glyph of Burning Embers"
http://www.wowwiki.com/Glyph_of_Burning_Embers

b)Minor
"Glyph of Eye of Kilrogg"
http://www.wowhead.com/item=43391

"Glyph of Hand of Gul'dan"
http://www.wowhead.com/item=42453

"Glyph of Nightmares"
http://www.wowhead.com/item=42457

"Glyph of Soulwell"
http://www.wowhead.com/item=43394

---

```
                                         |Hunter|
```

1) Talents
Tok i jica

2) Glyphs

a)Major
"Glyph of Explosive Trap"
http://www.wowhead.com/item=42908

"Glyph of Marked for Death"
http://www.wowwiki.com/Glyph_of_Marked_for_Death

b)Minor
nqmam inf.

---

```
                                         |Priest|
```

1) Talents
Tok i jica.

1) Glyphs

a)Major
"Glyph of Holy Nova"
http://www.wowhead.com/item=42401

"Glyph of Inner Focus"
http://www.wowwiki.com/Glyph_of_Inner_Focus

"Glyph of Psychic Scream"
http://www.wowhead.com/item=42410

"Glyph of Shadow Word: Death"
http://www.wowhead.com/item=79514

"Glyph of Mind Flay"
http://www.wowhead.com/item=79513

"Glyph of Mind Spike"
http://www.wowhead.com/item=45758

"Glyph of Dark Binding"
http://www.wowwiki.com/Glyph_of_Dark_Binding

b)Minor
"Glyph of Shadow Ravens"
http://www.wowhead.com/item=43342

"Glyph of Shadow"
http://www.wowhead.com/item=77101

"Glyph of Dark Archangel"
http://www.wowhead.com/item=43374

---

```
                                         |Druid|
```

1) Talents
"Typhoon"
http://www.wowhead.com/spell=132469

"Force of Nature"
http://www.wowhead.com/spell=106737

2) Glyphs

a)Major
"Glyph of Savagery"
http://www.wowhead.com/item=40923

"Glyph of Ferocious Bite"
http://www.wowhead.com/item=48720

"Glyph of Hurricane"
http://www.wowhead.com/item=40920

"Glyph of Lifebloom"
http://wowpedia.org/Glyph_of_Lifebloom

"Glyph of Rejuvenation"
http://www.wowhead.com/item=40913

"Glyph of Shred"
http://www.wowhead.com/item=40901

"Glyph of Innervate"
http://www.wowhead.com/item=40908

"Glyph of Master Shapeshifter"
http://www.wowhead.com/item=44928

"Glyph of Charm Woodland Creature"
http://www.wowhead.com/item=43335

b)Minor
"Glyph of The Predator"
http://www.wowhead.com/item=67486

"Glyph of THe Cheetah"
http://www.wowhead.com/item=89868

"Glyph of the Stag"
http://www.wowhead.com/item=40900

---

```
                                         |Rogue|
```

1) Talents
Tok i jica.

2) Glyphs

a)Major
"Glyph of Deadly Momentum"
http://www.wowhead.com/item=45766

"Glyph of Debilitation"
http://www.wowwiki.com/Glyph_of_Debilitation

---

```
                                         |Shaman|
```

1) Talents
"Totemic Projection"
http://www.wowhead.com/spell=108287

"Ancestral Swiftness"
http://www.wowhead.com/spell=16188

"Call of the Elements"
http://www.wowhead.com/spell=108285

"Conductivity"
http://www.wowhead.com/spell=108282

2) Glyphs

a)Major
"Glyph of Fire Nova"

---

```
                                         |Paladin|
```

1) Talents
6 tochki

2) Glyphs

a)Major
"Glyph of the Battle Healer"
http://www.wowhead.com/item=81956

"Glyph of Divinity"
http://www.wowhead.com/item=41108

"Glyph of Harsh Words"
http://www.wowhead.com/item=41107

"Glyph of Protector of the Innocent"
http://www.wowhead.com/item=66918

"Glyph of Rebuke"
http://wowpedia.org/Glyph_of_Rebuke

"Glyph of Blessed Life"
http://www.wowhead.com/item=41110

"Glyph of Beacon of Light"
http://www.wowhead.com/item=45741

"Glyph of Hammer of the Righteous"
http://www.wowhead.com/item=45742

"Glyph of Consecration"
http://www.wowhead.com/item=41099

b)Minor
"Glyph of Mounted King"
http://www.wowhead.com/item=43340

"Glyph of Winged Vengeance"
http://www.wowhead.com/item=43366

"Glyph of the Luminous Charger"
http://www.wowhead.com/item=41100

"Glyph of Contemplation"
http://www.wowhead.com/item=43365

---

```
                                         |Monk|
```

1) Talents
"Chi Wave"
http://www.wowhead.com/spell=115098

2) Glyphs

a)Major
"Glyph of Crackling Jade Lightning"
http://www.wowwiki.com/Glyph_of_Crackling_Jade_Lightning

"Glyph of Mana Tea"
http://www.wowhead.com/item=85692

"Glyph of Breath of Fire"
http://www.wowhead.com/item=85685
- diminishing effecta ne raboti, t.e disorienta vinagi si e 3sec nezavisimo dali go puska za purvi ili 20-ti put.

"Glyph of Leer of the Ox"
http://www.wowhead.com/item=87894

b)Minor
"Glyph of Flying Serpent Kick"
http://www.wowhead.com/item=87882
- Всичко описано по-горе е на база тестове с играчи от сървъра и информацията е обща. Ако има нещо което сме изпуснали, който желае може да напише за пропуските.

**Comment by Attractivee** [comment]
Paladin Talant:
[Execution Sentence] - мога да я пускам само върху себе си, когато я пусна на друг нищо не става.
http://www.wowhead.com/spell=114157
