### ISSUE TITLE
Ubivate ni s tiq bleeding effects....

### ISSUE THREAD

**Issue by smotanqci** [DragonFire/panda#472]
Bleeding effectite pravqt mnoooooooooooooooooooooogooooooooooooooooooooooooo poveche dmg ot kolkoto trqbva!

**Comment by FALL1N1** [comment]
Sad level: OVER 9000!
Kato pravish report pone opishi koi bleed kakvo shto pravi vmesto da obijdash i da sadvash.

**Comment by Attractivee** [comment]
"smotanqci" :D, смотаняка си ти в случая.С простотия няма да помогнеш за фиксването на Bleeding Effects в случая, най-много да изнервиш някои.

**Comment by tribaler0** [comment]
haide pyrvo pregledai reportite v githuba sled tva si pishi typotiite a ? Normalnite hora tuk postvame bugove i koe kak trqbva da raboti a ne se oplakvame kelesh! Stegni se !

**Comment by Larua** [comment]
mortal strike 150k pri 44% pvp reselience? sadnah

**Comment by FALL1N1** [comment]
FULL CD прави и повече. Давайте снимки на тея Warriori които дънят по 150-200к тъй като аз end gear не мога да вкарам повече от 150к. Намирисва ми на нещо... :)
