### ISSUE TITLE
.......

### ISSUE THREAD

**Issue by smotanqci** [DragonFire/panda#473]
Zashto ne podarite servera na nqkoi , koito moje da se spravi s poddryjkata na servera (demek vseki drug osven vas) i kato si uchenik zashto vyobshte se hvashtash da pravish neshto , koeto ne ti e po silite ? ili pravi neshto kato horata ili ne se hvashtai s nego. I kato davash prava na nqkoi da byde GM , za kvo negovi poznati ili tam kvito sa , se dyrjat nadmenno , psuvat i obidat na volq , a kogato im kajesh neshto, poluchavash ban ?

**Comment by FALL1N1** [comment]
Ако ти харесва и си търпелив както всички останали ще играеш, ако не.. пускай мигача ;)
