### ISSUE TITLE
Items: Dreadful Gladiator's Insignia of Victory - Class A

### ISSUE THREAD

**Issue by Larua** [DragonFire/panda#475]
http://www.wowhead.com/item=84495/dreadful-gladiators-insignia-of-victory

Predmeta ne e tochno tozi, no tozi koito e v 5.0.0 go nqma v wowhead. Nashiq e lilav i sus suvsem malko po qk stats. Posledniq equip bonus dava shans za uvelichavane na silata s 3017. Vmesto tova obache pri aktivirane na efekta dava samo 91. Tashak, ograbiha ni ot 2900++ sila FAAAAAAK. Fix plz.

**Comment by tribaler0** [comment]
Pishe 4e dava 91 no fakti4eski ako zagledash statsovete si shte se uverish 4e dava 3017 ;)

**Comment by FALL1N1** [comment]
Проблем с CLIENT-а, не може да бъде оправено от сървъра.
