### ISSUE TITLE
Many many bugs - DragonFire Best Bugged Server EVER !!!

### ISSUE THREAD

**Issue by tribaler0** [DragonFire/panda#524]

**Comment by AnTOLI** [comment]
:+1:

**Comment by Enragelolz** [comment]
Vednaga, ama vednaga ti linkvam - http://vbox7.com/play:92e19ed4cb, eto tova neshto se sluchva v blizzard i ne mi izlizai s nomera che picha e END GEAR, zashtoto ne e, vij mu life-a -  350k, koeto shte reche dreadful-che... 56sec mojesh da gi vidsh 360k ;)

**Comment by Enragelolz** [comment]
END GEAR i ima po-malko life ot mene s dreadful ...?

**Comment by Attractivee** [comment]
Така е, аз като репортна и на секундата се взимат мерки, също така всички questove, spellove, talanti репортнати от мен са фикснати на 100%.
Тези дни, ще репортна няколко боса в Heart of Fear, както и Black Market-a, девелопери стягаите се :D:D:D:D:D:D:D

Enrage, не се хаби, той горкия това дето го говори само той си го вярва.

**Comment by Mympa** [comment]
замислете се малко преди да пишете.. има близардски хънтър с 576 итем левел и на гарош прави по 400к дмг ... я се дръжте малко... къв е тоя дреадфул геар .. за 100 140к дмг макс... фул енчант и джемнат... пак да си погледнат формулите за спеловете
