### ISSUE TITLE
Innkeeper Turk

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#57]
http://www.wowhead.com/npc=49762/innkeeper-turk
Innkeepera не работи, тоест неможе да си направите домът при него.

**Comment by DarkAngel39** [comment]
UPDATE `creature_template` SET `npcflag`=`npcflag`+65536 WHERE `npcflag` != `npcflag`|65536 AND `entry`=49762;

**Comment by 3DViking** [comment]
мерси, качил съм го. След рестарт трябва да е ок. МЕРСИ!
