### ISSUE TITLE
 Quest: [84] [Torn Ground](Part 3 of 9)

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#59]
При този quest трябва да убием 3 Tentacle of iso'rath - http://www.wowhead.com/npc=45394/tentacle-of-isorath
Но след като ги убием, не отчита че са убити...

**Comment by 3DViking** [comment]
готово, след рестарт ще е наред.

**Comment by Funkedelica** [comment]
куеста си работеше и преди ,но не се биеха елитите ,а имаше нормални мобове ,който нямат форма и не се виждат ,но са близо до другите и сами ви излизат като обикаляте
