### ISSUE TITLE
Какво става с сървъра..!!!

### ISSUE THREAD

**Issue by AnTOLI** [DragonFire/panda#604]
Спрян ли е проекта по сървъра или да очакваме чудо да се случи. Поне даите някакъв отговор.
Нито по Facebook се пише никои не знае какво става с сървъра...

**Comment by Min4AKK** [comment]
https://github.com/DragonFire/panda/issues/253#issuecomment-39013686

Ami shte ima tonove updati.Kazano li e-kazano e!Obeshtano li e -obeshtano e!Izpulneno li e-ne e izpulneno!MInalo li e 1 godina-pochti!Ima li neshto raboteshto-nqma neshto raboteshto ->Ima li budeshte i nadejdi za servera-nqma budeshte i nadejdi za servera! ->Ima li smisal da se qdosvam-nqma smisal da se qdosvam ->Ima li smisal da igraq-nqma smisal da igraq! ;)

**Comment by Min4AKK** [comment]
tova sashtoto shte vaji za Molten WoW,koito si ima veche 5.4.2 rabotesht MoP (2 realma daje) i shte vaji sushtata i informaciq,samo che shte bude s protivopolojen na gorniq za DF rezultat i smisal

**Comment by AnTOLI** [comment]
Предлагам да се махнат да всички бановете от играчи и да се почне на ново. И без това в сървъра има  малко хора....

**Comment by Bleedeyes** [comment]
Няма кой да играе... времето лекува, но също така и убива всичко... КРАЙ !!! приемете го

**Comment by Larua** [comment]
Veche e instant 90 pravete geroi i davaite da pravim bg

**Comment by Steveg1234566** [comment]
Не е инстант 90!

**Comment by FALL1N1** [comment]
Нито ще се спира нито лича. Пандария (5.0.5) остава без поддръжка, което означава че няма да правя голями и сложни фиксове(нови райдове, дънджани) а малките (куестипандата/таланти/магии) ще продължавам да оправям. Относно 5.4.8 това ядро аз съм го разработил (стар клон от Тринити 4.3.4), оправил съм повечето структури на опкодовете за да може да се играе. Когато оправя арените и батълграундите ще го пуснем БЕТА-ЛАЙВ фънка за да може да играете ПВП на него. Повечето (ако не всички) магии работят като хората. Изключил съм акшън хаус-а, банкерите, всички дънджъни и райдове както и куести. Ще е чисто и просто САМО ПВП!

**Comment by gghost** [comment]
Извинете, но...НА ВАС ИЗОБЩО ПУКА ЛИ ВИ ЗА ТОЗИ СЪРВЪР...нали за да съществува  са необходими и хора,които да играят в него,а това няма как да се случи само с оправянето на таланти и магии..Май единствената ви и конкретна цел е да ни изгоните...

**Comment by FALL1N1** [comment]
@gghost Дай по-добра идея. и да, щом оправям бъгове и т.н безплатно значи ми пука и харесва да работя тук.

**Comment by gghost** [comment]
Сърдечни поздравления, относно това, че проявихте някаква активност !!!!!!...но бяха необходими месеци да изезете от дебрите на мълчанието и да хвърлите някаква яснота на нас простолюдието, които щом устискахме и устояхме на всичките тези бъгове, на пълната липса на информация, относно всичко,,,значи сигурно и на нас ни харесва да бъдем тук и вярваме във ВАС!

**Comment by Mympa** [comment]
а някой да е помислил за хората които НЕ ХАРЕСВАТ ПВП-ТО ? ТЕ КАКВО ПРАВЯТ ? МАХАТ СЕ ОТ СЪРВЪРА ..ТАКА ЛИ ?

**Comment by FALL1N1** [comment]
@Mympa имаш и близлайк 3.3.5 реалм с всички дънджъни(освен кос), всички райдове и магии работещи и имаш занимание.

**Comment by AnTOLI** [comment]
Cos че е оправите толкова ли е сложно да се оправи то и в другите дънджъни се бъгва некои босс. ;с
Поне оправете некои постижения при  убиване да боса да го вземем.
За бг та не може и да се говори  като няма 12 80  да пишат направете неква система за тия бг та.

**Comment by gghost** [comment]
Преиначавате думите и смисъла на запитването на @Mympa...едва ли  би задал въпроса си в този раздел, ако му се играеше в 3.3.5 реалма. И едва ли с този отговор бихте ни привлекли там. Видяхте, че въпреки усилията, които положихте, там няма никакъв интерес и посещаемост..Еуфорията бе точно за около месец и нещата станаха по.зле и отпреди година . С две думи се оказахте-"от два стола, та на земята",

**Comment by Sweg420** [comment]
"ГЛЕДАЙТЕ НИ 3.3.5 РЕАЛМА И СЕ РАДВАЙТЕ". Момчета толкова години играе ли се едно и също, трябва прогрес и вашия опит за такъв беше пълен провал. Ако ще правите нещо, правете инъче не заблуждавайте хората.Губите и последните капки доверие, което имахме към вас.

**Comment by Mympa** [comment]
JunkyBulgaria.. знам че работиш, колкото можеш, разбирам те напълно и знам че не е лесно, когато си сам, ама ... 335 при положение че има MOP i WoD не мислиш ли че е меко казано подигравателно. Че аз Лич Кинга сам го бия бе пич, мене райд не ми трябва за него.. Прочети малко, как се бият сега ЛК и Ката райдовете... айде моля ти се .. не ме карай да се смея с глас. И не ми казвайте сега, ЕМИ КАТО ИСКАШ ДА ИГРАЕШ ИДИ НА БЛИЗАРД И СИ ИГРАЙ ТАМ. Аз по принцип там си играя и сега, но ми е болно щото преди да почна там, играх на Драгон-а 2 години и знам какво беше 2005 2006 година. ПВП-то е лесно, когато са оправени магиите, доколкото знам, не всичко работи коректно(магии+таланти), за да кажете че ще пускате пвп на 548 това значи да работят поне 85+ % от таланти и магии на всички класове. Знам лесно е да се критикува, но и с пвп-то няма да се стигне до никъде, защото ако сметнем че за пве трябва да се скриптват босовете и маса още други неща, то за пвп пък трябва да има минимум 85% работещи магии и таланти. Може и да бъркам ама ако не бачка някой талант.... от последните...има ли смисъл да се играе :-) или ако не бачкат бонусите от 2-те или 4-те пвп части?

**Comment by FALL1N1** [comment]
@Mympa работя и по пандария, имам още 15-20 неща от списъка си за оправяне (като Банкерите, Гуилд банк, Аукционна къща, Петове и Арените трябва да се пренаписват наново тъй като от патч 5.4.0 до сега беше с НПЦ сега е директно от прозорчето и няма арена тийм-ове. Талантите / магиите работят над 80% което е доста добре като начало за ПВП сървър, а относно ПВЕ ще кодирам всички босове с базови магии, текстове и фази за да може да ги правите а не да тъпеете. КУЕСТОВЕ-те са нещо, което ще е доста трудно (не толкова трудно колкото ще отнеме прекалено много време) и за това ще ги правим ауто-изпълняеми. Така че от сега обещавам ЧЕ ЩЕ ИМА ПАНДА 5.4.8 _НО_ трябва да имате търпение защото работя сам по фиксовете а през това време имам живот и училище пред мен.

Поздрави,
Емилиян

**Comment by FALL1N1** [comment]
Както обещах, пуснах пълен улдуар, арени + батълграунди и ПВП реалм на 3.3.5, следва пандария!

**Comment by AnTOLI** [comment]
Оправи некои постижения много хора това правят.!
