### ISSUE TITLE
" Welcome to your future! "

### ISSUE THREAD

**Issue by Min4AKK** [DragonFire/panda#607]
След продължителен разговор с един от ГМтата на Драгонфайър стана ясно какво може да се очаква в най-скоро време по отношение на 5.0.5 сървъра.Ето и следните неща: 

http://s29.postimg.org/4iftoheef/Wo_WScrn_Shot_011515_214724.jpg

http://s13.postimg.org/ij2n59prr/Wo_WScrn_Shot_011515_214855.jpg

http://s21.postimg.org/l7vys3i0n/Wo_WScrn_Shot_011515_215137.jpg

http://s3.postimg.org/tuvhi4q37/Wo_WScrn_Shot_011515_220042.jpg

http://s24.postimg.org/zfg50b4x1/Wo_WScrn_Shot_011515_215447.jpg

**Comment by Min4AKK** [comment]
http://s23.postimg.org/vs7s3na6j/Wo_WScrn_Shot_011515_220350.jpg

**Comment by gghost** [comment]
Много жалко, че информация от този,  или какъвто и да било тип, касаещ всички ни се получава по този начин..Защо поне един от тези ГМ не излезе с ясно становище и не го оповести публично. Повече от година всичко се случва по този подмолен начин, държат  хората в неведение, макар да нямаше нищо срамно да си признаят още тогава, че не им се получават нещата и да не  карат доста от хората да влагат усилия и напразни надежди." Възхищавам " се на наглостта и безочието, на пълната безпристрастност и най-вече на липсата на всякаква отговорност, спрямо поетите ангажименти и обещания, на които всички се наслушахме. Чудно ми е дали наистина си вярват, че затваряйки този реалм разчитат, че някой от нас, от всички "сърбали горчивата попара" би се върнал да играе някога отново , в който и да било реалм на DragonFire..Всеки си пати  от собствената глава, тъй че, Уважаеми ГМ-та, не се чудете защо няма хора, всъщност едва ли се и чудите, Вие сами ги изгонихте. Кадърни и имащи желание за игра хора сега пълнят чуждите сървъри, и вероятно не си задаат въпроси от типа "Дали ще ме пусне да логна или ще е затворен сървъра".Не знам дали го осъзнавате, но се ИЗЛОЖИХТЕ В ГЛОБАЛЕН МАЩАБ!!!!!

**Comment by Mympa** [comment]
както винаги ... се говори много .. аз бях наясно че Пандариата няма да тръгне добре на Драгон-фире, но си премълчах, не исках да го говоря предварително,Истина е че така поднесена информацията, си е меко казано нагло, при положение че има хора които все пак играят, колкото и да е бъгав сървъра,поне да имаше малко уважение към тези хора.Пандария няма никъде работеща на 80%, обаче няма и хора които да помагат за оправянето. и истина е че повечето ужким пандария сървъри са пвп ориентирани и пве играчите ще търсят други начини да играят.

**Comment by opalq** [comment]
За Пандария ясно, но и wotlk вече умря и никои нищо не казва. Нали щеше всичко да е различно, с нов екип, поддръжка и т.н. Имаше някакъв hype в началото, направиха се 1-2 update, от 3-ма online станаха 100-на, и толкова. Накрая пак стана както преди - никакво отношение към играчите, никакви новини, абсолютно нищо. Напишете в сайта- "няма да има сървър" и готово. Или "прави се еди- какво си". Толкова ли е трудно?. Има някакъв "Tournament " realm, за който пак нищо не е споменато, и на който също няма да има хора. Не може последната новина да е от октомври месец.. 
Отново всичко остана на произвола на съдбата.

**Comment by Min4AKK** [comment]
Ами за 3.3.5 също планират да го затворят евентуално и да остане само този бъдещ 5.4.8 ПВП ориентирания (забравих да направя СС и на това)

**Comment by Mympa** [comment]
и как ще ме накараш да играя на 335 ... незнам само ... при положение че има други които се държат по добре от драгон фире :-) не можеш да ме свалиш от кон и да ме караш да яздя кокошка

**Comment by gghost** [comment]
Всички сме на това мнение,Mympa...дано обаче, тези от които зависи всичко имат достатъчно разум да го проумеят

**Comment by Mympa** [comment]
за жалост никой от тези които ги е грижа за сървъра не ги интересува какво ще бъде после. Най лесно е да се направи пвп, остава само да трием героите си и да си търсим други варианти за игра на тази игра :-) ...... за жалост

**Comment by FALL1N1** [comment]
Няма да се закрива, най-много да го качим на 5.4.8.. Не че ще е нещо по-лошо от сега но ще има повече неща за разкриване, изпълняване на куести и т.н. :)

**Comment by Mympa** [comment]
абе вие 505 не можете да оправите, сега 548 ще слагате с siege of Orgrimar, timeless isle и ъпграйде да епичните итеми 4-ри пъти.. Сега не почвайте да се сърдите, аз си играя по принцип на Близард, и сега когато кажете : айде стой си на Близард , какво се занимаваш тука да дразниш, казвам аз съм си на Близард, и съм играл и да този сървър, така че този сървър ми е слабост някаква.И много ми е интересно, как ще се бият целестиал босовете на тимелес които дропят и пвп итеми. Изпълняването на куестове на пвп сървър е сведено до мимимум, и преди да пишат нещо хората които ще пускат 548, да погледнат какви да били предишните пачове:540, 541,542, 547 и после да мислят за 548. Дано когато се пусне, да работи що годе коректно и с малко повече баланс. :-) Все пак съм скептично настроен, но все пак пожелавам успех и не ме разбирайте погрешно, не искам този сървър да се затваря, а да се работи по него !!!

**Comment by DarkAngel39** [comment]
5.0.5 няма никаква потдръжка, поради простата причина че няма официален проект, който да разработва кода. Да не говорим, че пача е стар и повечето неща са променени. А що се отнася до 5.4.8 - http://www.projectskyfire.org/
Също така, Trinity Core работят по WOD и би било по-добре, в бъдеще да пренесат 3.3.5 реалма на 6.Х.Х, вместо да се затваря.

**Comment by AnTOLI** [comment]
Кога че се пусне 5.4.8.

**Comment by AnTOLI** [comment]
Сега пандата ли че се спира и че се качим до 5.4.8 или 3.3.5 реалма.
Пуснете някои евент на 3.3.5 поне да имаме да правим нещо като влизаме тама.

**Comment by Bleedeyes** [comment]
било, каквото било.... почвайте Blizz, аз вече почнах понеже още не ми се разделя с wow.... идвайте в Sylvanas и бг гилдий има даже :)

**Comment by gghost** [comment]
На някой стана ли му ясно нещо конкретно ?!??

**Comment by FALL1N1** [comment]
@Mympa искам да те нахраня едно хубаво.

```
@gghost @Bleedeyes @AnTOLI @DarkAngel39 @opalq @Min4AKK

Нито пандата ще се спира нито лича. Пандария (5.0.5) остава без поддръжка, което означава че няма да правя голями и сложни фиксове(нови райдове, дънджани) а малките (куести/таланти/магии) ще продължавам да оправям. Относно 5.4.8 това ядро аз съм го разработил (стар клон от Тринити 4.3.4), оправил съм повечето структури на опкодовете за да може да се играе. Когато оправя арените и батълграундите ще го пуснем БЕТА-ЛАЙВ фънка за да може да играете ПВП на него. Повечето (ако не всички) магии работят като хората. Изключил съм акшън хаус-а, банкерите, всички дънджъни и райдове както и куести. Ще е чисто и просто САМО ПВП!
```
