### ISSUE TITLE
Ronalldinho Howling Fjord Questi

### ISSUE THREAD

**Issue by Ronalldinho** [DragonFire/panda#608]
Zdr eto tova sa Questite za Howling det nqmat loot ot Npc ta ta 1 Q http://www.wowhead.com/item=33289 2 Q http://www.wowhead.com/item=33314 3 Q http://www.wowhead.com/item=33961 4 Q http://www.wowhead.com/item=34090 a eto ti i imenata kak se kazvat 1 Q Gjalerbron Attack Plans 2 Q Vrykul Scroll of Ascension 3 Q Scourge Device 4 Q Mezhen's Writings tova e Moga sa6to da ti napi6a ot kogo trq da padat questite ako trqbva Npc tata za Aliance sa teq Questi Fix pls ! :)

**Comment by FALL1N1** [comment]
Оправени, и този репорт е за WoTLK!

**Comment by Ronalldinho** [comment]
to e hubavo opraven no kato varne6 questite v campa tam ne ti dava drugite da prodalji6 da dovari6 zonata vs edno ni6to nqma zna4enie znaem lesniq variqt i taka bb !
