### ISSUE TITLE
Orgrimmar асансьори не работят.

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#63]
Искам да съобщя, че може би един или два от асансиорите в Orgrimmar работят, останалите НЕ работят.

**Comment by Mympa** [comment]
еми те са дървени все пак ... :) чупят се :)

**Comment by Attractivee** [comment]
И на майка ти п*тката е дървена ама целия ДФ + още 2-3 сървъра немогат да я счупят.
