### ISSUE TITLE
NPC: Aeonaxx <Mate of Aeosera>

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#65]
Това е Rare NPC от което пада моунт 100%, но е бъгнато и се spawn-ва постоянно.
http://www.wowhead.com/npc=50062#.
Най-ниския възможен spawntime е 6 часа, а най-високия 22 часа.
http://www.wowwiki.com/Aeonaxx

**Comment by Mympa** [comment]
е това не е проблем... :)

**Comment by imbaskill** [comment]
sigurno e vzel mounta i ne iska drugite da go imat su6to
