### ISSUE TITLE
NPC: Taran Zhu <Lord of the Shado-Pan>

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#73]
Taran Zhu <Lord of the Shado-Pan> - http://www.wowhead.com/npc=66665
Това NPC липса от мястото на което трябва да бъде и неможе да се мине quest:
 [85] [Prowler Problems], защото трябва да се върне при горепосоченото NPC.

**Comment by FALL1N1** [comment]
На мястото си е.
