### ISSUE TITLE
NPC: Elder Lusshan

### ISSUE THREAD

**Issue by Attractivee** [DragonFire/panda#83]
http://www.wowhead.com/npc=54960#.
Това NPC атакува Horde и неможе да върнем  [85] [Carpe Diem]
Quest-а по принцип е за Alliance само, но може да се минава и от хордите.
NPC: http://www.wowhead.com/npc=54960#.
Quest: http://www.wowhead.com/quest=29906

**Comment by Mympa** [comment]
пич куеста е САМО ЗА АЛИАНСЕ... никаква хорда няма там 
хордата го връщат на друго място..

**Comment by FALL1N1** [comment]
Вече е на мястото си.
