### ISSUE TITLE
Bugnat geroi

### ISSUE THREAD

**Issue by preakpwz** [DragonFire/panda#93]
gm bugna mi se geroq, zarejda pocti do kraq no nemoga da flqza

**Comment by tedo12** [comment]
I az nemoga da vlezna s moq,a i 4akam ot 2 sedmici 3 nqkoi da mi pomogne ot support pisha tiket spamq v world i nikoi ne pishe..

**Comment by preakpwz** [comment]
em she chakame da ni turkat achivmentite
